import { ArrowDownRight, ArrowUpRight, BriefcaseBusiness, TrendingUp } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { api } from '../api'
import { PageHeader } from '../components/PageHeader'
import { useProjects } from '../projects'

type FinanceEvent={id:string;type:'receipt'|'report'|'transfer'|'estimate';amount:number;status:string;projectId:string;projectName:string;eventDate:string}
type Period='3m'|'6m'
export function Analytics(){
 const {projects}=useProjects();const [events,setEvents]=useState<FinanceEvent[]>([]);const [loading,setLoading]=useState(true);const [period,setPeriod]=useState<Period>('6m')
 useEffect(()=>{api<{events:FinanceEvent[]}>('/finance-events').then(data=>setEvents(data.events)).finally(()=>setLoading(false))},[])
 const confirmed=useMemo(()=>events.filter(event=>event.status==='confirmed'&&event.type!=='estimate'),[events]);const months=useMemo(()=>buildMonths(period==='3m'?3:6,confirmed),[confirmed,period]);const income=months.reduce((sum,item)=>sum+item.income,0);const expense=months.reduce((sum,item)=>sum+item.expense,0);const projectRows=useMemo(()=>projects.map(project=>{const projectEvents=confirmed.filter(event=>event.projectId===project.id);return{name:project.name,income:projectEvents.filter(event=>event.type==='receipt').reduce((sum,event)=>sum+event.amount,0),expense:projectEvents.filter(event=>event.type==='report'||event.type==='transfer').reduce((sum,event)=>sum+event.amount,0)}}).sort((a,b)=>(b.income+b.expense)-(a.income+a.expense)),[projects,confirmed])
 return <main className="light-page"><div className="mobile-page analytics-page"><PageHeader title="Аналитика"/><div className="analytics-period"><button className={period==='3m'?'is-active':''} onClick={()=>setPeriod('3m')}>3 месяца</button><button className={period==='6m'?'is-active':''} onClick={()=>setPeriod('6m')}>6 месяцев</button></div>{loading?<p className="counterparty-empty-events">Загрузка…</p>:<><section className="analytics-kpis"><article><ArrowUpRight/><span>Поступления</span><strong>{money(income)} ₽</strong></article><article><ArrowDownRight/><span>Расходы</span><strong>{money(expense)} ₽</strong></article><article className={income-expense<0?'is-negative':''}><TrendingUp/><span>Результат</span><strong>{money(income-expense)} ₽</strong></article></section><section className="analytics-card"><h2>Динамика денег</h2><p>Подтверждённые операции по месяцам</p><MonthlyChart data={months}/><div className="chart-legend"><span><i className="income"/>Поступления</span><span><i className="expense"/>Расходы</span></div></section><section className="analytics-card"><h2>Проекты</h2><p>Поступления и расходы по проектам</p>{projectRows.length?<div className="project-chart">{projectRows.map(row=><ProjectBar key={row.name} {...row}/>)}</div>:<div className="analytics-empty"><BriefcaseBusiness/>Проектов пока нет</div>}</section></>}</div></main>
}
function MonthlyChart({data}:{data:{label:string;income:number;expense:number}[]}){const max=Math.max(1,...data.flatMap(item=>[item.income,item.expense]));return <div className="monthly-chart">{data.map(item=><div className="month-column" key={item.label}><div><i className="income" style={{height:`${Math.max(item.income?4:0,item.income/max*100)}%`}} title={`Поступления: ${money(item.income)} ₽`}/><i className="expense" style={{height:`${Math.max(item.expense?4:0,item.expense/max*100)}%`}} title={`Расходы: ${money(item.expense)} ₽`}/></div><span>{item.label}</span></div>)}</div>}
function ProjectBar({name,income,expense}:{name:string;income:number;expense:number}){const max=Math.max(1,income,expense);return <article><strong>{name}</strong><div><span>Поступления</span><i><b className="income" style={{width:`${income/max*100}%`}}/></i><em>{money(income)}</em></div><div><span>Расходы</span><i><b className="expense" style={{width:`${expense/max*100}%`}}/></i><em>{money(expense)}</em></div></article>}
function buildMonths(count:number,events:FinanceEvent[]){const now=new Date();return Array.from({length:count},(_,index)=>{const date=new Date(now.getFullYear(),now.getMonth()-count+index+1,1);const key=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`;const selected=events.filter(event=>event.eventDate.startsWith(key));return{label:date.toLocaleDateString('ru-RU',{month:'short'}).replace('.',''),income:selected.filter(event=>event.type==='receipt').reduce((sum,event)=>sum+event.amount,0),expense:selected.filter(event=>event.type==='report'||event.type==='transfer').reduce((sum,event)=>sum+event.amount,0)}})}
function money(value:number){return new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(value)}
