import { ArchiveRestore, History, Trash2 } from 'lucide-react'
import { useEffect, useState } from 'react'
import { api } from '../api'
import { PageHeader } from '../components/PageHeader'

type ArchivedProject={id:string;name:string;customer:string;archivedAt:string}
type DeletedEvent={id:string;type:string;amount:number;projectName:string;description:string;eventDate:string;deletedAt:string}
export function Archive(){const[projects,setProjects]=useState<ArchivedProject[]>([]);const[events,setEvents]=useState<DeletedEvent[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');async function load(){setLoading(true);setError('');try{const[projectData,eventData]=await Promise.all([api<ArchivedProject[]>('/projects/archived'),api<DeletedEvent[]>('/finance-events/deleted')]);setProjects(projectData);setEvents(eventData)}catch(cause){setError(cause instanceof Error?cause.message:'Не удалось загрузить архив')}finally{setLoading(false)}}useEffect(()=>{void load()},[]);async function restoreProject(id:string){await api(`/projects/${encodeURIComponent(id)}/restore`,{method:'POST'});await load()}async function restoreEvent(id:string){await api(`/finance-events/${id}/restore`,{method:'POST'});await load()}return <main className="light-page"><div className="mobile-page archive-page"><PageHeader title="Архив"/>{error&&<p className="form-error">{error}</p>}{loading?<p className="empty-state">Загрузка…</p>:<><section><h2><Trash2/>Проекты ({projects.length})</h2>{projects.length?projects.map(item=><article key={item.id}><span><strong>{item.name}</strong><small>{item.customer||'Заказчик не указан'} · удалён {format(item.archivedAt)}</small></span><button onClick={()=>void restoreProject(item.id)}><ArchiveRestore/>Восстановить</button></article>):<p>Удалённых проектов нет</p>}</section><section><h2><History/>Финансовые события ({events.length})</h2>{events.length?events.map(item=><article key={item.id}><span><strong>{labels[item.type]||item.type} · {money(item.amount)} ₽</strong><small>{item.projectName||item.description||'Без описания'} · удалено {format(item.deletedAt)}</small></span><button onClick={()=>void restoreEvent(item.id)}><ArchiveRestore/>Восстановить</button></article>):<p>Удалённых событий нет</p>}</section></>}</div></main>}
const labels:Record<string,string>={receipt:'Поступление',report:'Отчёт',transfer:'Перевод',estimate:'Смета'}
function format(value:string){return new Date(value).toLocaleDateString('ru-RU')}
function money(value:number){return new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(value)}
