import { Check, CircleDashed, Filter, Home, Search, UserRound, WalletCards, X } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { api } from '../api'
import { PageHeader } from '../components/PageHeader'

type EventType = 'receipt' | 'report' | 'transfer' | 'estimate'
type Status = 'pending' | 'confirmed' | 'rejected'
type HistoryEvent = { id: string; counterpartyId: string; counterpartyName: string; type: EventType; amount: number; status: Status; projectId: string; projectName: string; description: string; eventDate: string; receiptDestination: string; tag: string; relatedPartyName: string; transferKind: string; createdAt: string }
const labels: Record<string,string> = { receipt: 'Поступление', report: 'Отчёт', transfer: 'Перевод', estimate: 'Смета', project: 'по проекту', agent_fee: 'агентского вознаграждения', company_fund: 'в Фонд компании', project_payment: 'Оплата или аванс по проекту', project_accountable: 'Перевод подотчётных средств по проекту', fund_payment: 'Оплата или аванс из Фонда компании', project_to_fund: 'Перевод из проекта в Фонд компании', fund_to_project: 'Перевод из Фонда компании в проект' }

export function EventHistory() {
  const navigate = useNavigate(); const [searchParams] = useSearchParams(); const projectId = searchParams.get('projectId') ?? ''; const fundOnly=searchParams.get('scope')==='company_fund';const requestedType=searchParams.get('type');const returnTo = projectId ? `/events?projectId=${encodeURIComponent(projectId)}` : fundOnly?`/events?scope=company_fund${requestedType?`&type=${requestedType}`:''}`:'/events'; const [events,setEvents]=useState<HistoryEvent[]>([]); const [query,setQuery]=useState(''); const [filter,setFilter]=useState<'all'|EventType>(()=>['receipt','report','transfer','estimate'].includes(requestedType||'')?requestedType as EventType:'all'); const [filterOpen,setFilterOpen]=useState(false); const [loading,setLoading]=useState(true)
  useEffect(()=>{api<{events:HistoryEvent[]}>('/finance-events').then((data)=>setEvents(data.events)).finally(()=>setLoading(false))},[])
  useEffect(()=>{sessionStorage.setItem('app101.eventHistoryReturnTo', returnTo)},[returnTo])
  const visible=useMemo(()=>{const normalizedQuery=query.toLowerCase().replace(/\s/g,'');return events.filter((event)=>(!projectId||event.projectId===projectId)&&(!fundOnly||isFundEvent(event))&&(filter==='all'||event.type===filter)&&`${title(event)} ${event.description} ${event.projectName} ${event.counterpartyName} ${event.relatedPartyName} ${event.tag} ${event.amount} ${money(event.amount)}`.toLowerCase().replace(/\s/g,'').includes(normalizedQuery))},[events,filter,query,projectId,fundOnly])
  return <main className="light-page"><div className="mobile-page event-history-page"><PageHeader title={fundOnly?'События Фонда компании':'История событий'} onBack={fundOnly?()=>navigate('/company-fund'):undefined}/><div className="history-search"><label className="search-field"><Search /><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Поиск" /></label><button className={filter==='all'?'':'is-active'} onClick={()=>setFilterOpen(true)} aria-label="Фильтр"><Filter /></button></div><p className="history-retention">События за последние 6 месяцев · максимум 500 записей</p>{loading?<p className="counterparty-empty-events">Загрузка…</p>:!visible.length?<p className="counterparty-empty-events">События не найдены</p>:<section className="history-list">{visible.map((event)=><article className={`history-event history-event--${event.type} history-event--${event.status}`} key={event.id} onClick={()=>navigate(`/counterparties/${event.counterpartyId}/events/${event.id}`, { state: { returnTo } })}><header>{event.status==='confirmed'?<Check/>:event.status==='rejected'?<X/>:<CircleDashed/>}<span>{title(event)}</span></header><small>{date(event.eventDate)} / {date(event.createdAt.slice(0,10))}</small>{event.description&&<strong>{event.description}</strong>}{event.tag&&<i>#{event.tag}</i>}{event.projectName&&<p><Home/>{event.projectName}</p>}<p><UserRound/>{event.relatedPartyName||event.counterpartyName}</p><footer><WalletCards/>{event.counterpartyName}<b>{money(event.amount)} ₽</b></footer></article>)}</section>}{filterOpen&&<div className="sheet-backdrop"><section className="history-filter"><div className="sheet-heading"><h2>Тип события</h2><button className="icon-button" onClick={()=>setFilterOpen(false)}><X/></button></div>{[['all','Все'],['receipt','Поступления'],['report','Отчёты'],['transfer','Переводы'],['estimate','Сметы']].map(([value,label])=><button className={filter===value?'is-active':''} key={value} onClick={()=>{setFilter(value as typeof filter);setFilterOpen(false)}}>{label}</button>)}</section></div>}</div></main>
}
function title(event:HistoryEvent){if(event.type==='transfer'&&event.transferKind)return labels[event.transferKind];if(event.type==='receipt'&&event.receiptDestination)return `${labels.receipt} ${labels[event.receiptDestination]}`;return labels[event.type]}
function date(value:string){const [year,month,day]=value.split('-');return `${day}.${month}.${year}`}
function money(value:number){return new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(value)}
function isFundEvent(event:HistoryEvent){if(event.type==='receipt')return event.receiptDestination==='company_fund';if(event.type==='report'||event.type==='estimate')return !event.projectId;return ['fund_payment','project_to_fund','fund_to_project'].includes(event.transferKind)}
