import { ChevronRight, HelpCircle, Trash2, X } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'
import { Navigate, useNavigate, useParams } from 'react-router-dom'
import { useAuth } from '../auth'
import { PageHeader } from '../components/PageHeader'
import { useCounterparties } from '../counterparties'
import { useExpenseArticles, type ProfitShare } from '../expenseArticles'
import { useProjects } from '../projects'

export function ExpenseArticleEditor() {
  const { projectId = '', articleId = '' } = useParams(); const navigate = useNavigate(); const { user } = useAuth(); const { projects } = useProjects(); const { counterparties } = useCounterparties(); const { articles, addArticle, updateArticle, deleteArticle } = useExpenseArticles(); const existing = articles.find((item) => item.id === articleId); const project = projects.find((item) => item.id === projectId)
  const [name, setName] = useState(existing?.name ?? ''); const [allowPositions, setAllowPositions] = useState(existing?.allowPositions ?? false); const [markupEnabled, setMarkupEnabled] = useState(existing?.markupEnabled ?? true); const [markupPercent, setMarkupPercent] = useState(String(existing?.markupPercent ?? 0)); const [costDifferenceEnabled, setCostDifferenceEnabled] = useState(existing?.costDifferenceEnabled ?? false); const [markupShares, setMarkupShares] = useState<ProfitShare[]>(existing?.markupShares ?? []); const [costShares, setCostShares] = useState<ProfitShare[]>(existing?.costDifferenceShares ?? []); const [shareMode, setShareMode] = useState<'markup'|'cost'|null>(null); const [error, setError] = useState('')
  const candidates = useMemo(() => [{ id: user?.id ?? '', name: user?.name ?? '', category: 'Основатель компании' }, ...counterparties.map((item) => ({ id: item.id, name: item.name, category: item.category }))].filter((item) => item.id), [counterparties, user]); const activeShares = shareMode === 'cost' ? costShares : markupShares; const setActiveShares = shareMode === 'cost' ? setCostShares : setMarkupShares
  if (!project || (articleId && !existing)) return <Navigate to={`/projects/${projectId}/expense-articles`} replace />
  function toggleRecipient(id: string, recipientName: string) { setActiveShares((current) => current.some((item) => item.counterpartyId === id) ? current.filter((item) => item.counterpartyId !== id) : [...current, { counterpartyId: id, name: recipientName, percent: 0 }]) }
  function submit(event: FormEvent) { event.preventDefault(); const enabledGroups = [markupEnabled ? markupShares : null, costDifferenceEnabled ? costShares : null].filter(Boolean) as ProfitShare[][]; if (enabledGroups.some((shares) => shares.length && shares.reduce((sum, item) => sum + item.percent, 0) !== 100)) { setError('Сумма долей каждого способа прибыли должна быть равна 100%'); return } const value = { projectId, name: name.trim(), allowPositions, markupEnabled, markupPercent: Number(markupPercent || 0), markupShares, costDifferenceEnabled, costDifferenceShares: costShares }; if (existing) updateArticle(existing.id, value); else addArticle(value); navigate(`/projects/${projectId}/expense-articles`, { replace: true }) }
  return <main className="light-page"><div className="mobile-page expense-editor-page"><PageHeader title={existing ? 'Изменить статью' : 'Добавить статью'} /><form onSubmit={submit}><p>Статьи расходов проекта позволяют группировать отчёты и сметы, а также управлять наценкой и распределением прибыли.</p><input className="expense-name" placeholder="Название" value={name} onChange={(event) => setName(event.target.value)} required/><ToggleRow label="Создание и изменение позиций" value={allowPositions} onChange={setAllowPositions}/><h2>Как формируется прибыль</h2><section className="profit-method profit-method--markup"><ToggleRow label="Наценка" value={markupEnabled} onChange={setMarkupEnabled}/>{markupEnabled && <><label>Процент наценки<input type="number" min="0" step="0.01" value={markupPercent} onChange={(event) => setMarkupPercent(event.target.value)}/></label><Shares shares={markupShares} onEdit={() => setShareMode('markup')}/></>}</section><section className="profit-method profit-method--cost"><ToggleRow label="Разница между ценой и себестоимостью" value={costDifferenceEnabled} onChange={setCostDifferenceEnabled}/>{costDifferenceEnabled && <Shares shares={costShares} onEdit={() => setShareMode('cost')}/>}</section>{error && <p className="form-error">{error}</p>}<button className="primary-button">Сохранить</button>{existing && <button className="expense-delete" type="button" onClick={() => { if (window.confirm('Удалить статью расходов?')) { deleteArticle(existing.id); navigate(`/projects/${projectId}/expense-articles`, { replace: true }) } }}><Trash2/>Удалить статью</button>}</form>{shareMode && <div className="sheet-backdrop" onClick={() => setShareMode(null)}><section className="share-editor" onClick={(event) => event.stopPropagation()}><header><button className="share-editor__close" type="button" onClick={() => setShareMode(null)} aria-label="Закрыть"><X /></button><h2>Получатели</h2><button className="share-editor__done" type="button" onClick={() => setShareMode(null)}>Готово</button></header><div className="share-candidates">{candidates.map((candidate) => { const selected = activeShares.find((item) => item.counterpartyId === candidate.id); return <article key={candidate.id}><button type="button" onClick={() => toggleRecipient(candidate.id, candidate.name)}><span>{candidate.name}<small>{candidate.category}</small></span><i className={selected ? 'is-selected' : ''}>{selected ? '✓' : ''}</i></button>{selected && <label>Доля<input type="number" min="0" max="100" value={selected.percent} onChange={(event) => setActiveShares((items) => items.map((item) => item.counterpartyId === candidate.id ? { ...item, percent: Number(event.target.value) } : item))}/>%</label>}</article> })}</div><p>Сумма долей: <b>{activeShares.reduce((sum, item) => sum + item.percent, 0)}%</b></p></section></div>}</div></main>
}
function ToggleRow({ label, value, onChange }: { label: string; value: boolean; onChange: (value: boolean) => void }) { return <label className="expense-toggle"><span>{label}<HelpCircle/></span><input type="checkbox" checked={value} onChange={(event) => onChange(event.target.checked)}/><i/></label> }
function Shares({ shares, onEdit }: { shares: ProfitShare[]; onEdit: () => void }) { return <div className="profit-shares"><header><span>Доли прибыли</span><button type="button" onClick={onEdit}>Изменить</button></header><small>Сумма долей: {shares.reduce((sum, item) => sum + item.percent, 0)}%</small>{shares.length ? shares.map((share) => <div key={share.counterpartyId}><span>{share.name}</span><b>{share.percent}%</b></div>) : <button type="button" onClick={onEdit}>Выбрать получателей <ChevronRight/></button>}</div> }
