import { Home, ListChecks, Paperclip, X } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'
import { Navigate, useLocation, useNavigate, useParams } from 'react-router-dom'
import { api } from '../api'
import { useAuth } from '../auth'
import { usePricing } from '../pricing'
import { useProjects } from '../projects'

type Destination = 'project' | 'company_fund'

export function NewEstimate() {
  const { counterpartyId = 'me' } = useParams(); const navigate = useNavigate(); const location = useLocation(); const { user } = useAuth(); const { projects } = useProjects(); const { priceLists } = usePricing()
  const navigationState = location.state as { returnTo?: string; projectId?: string } | null
  const [destination, setDestination] = useState<Destination>('project'); const [projectId, setProjectId] = useState(navigationState?.projectId ?? ''); const [expenseCategory, setExpenseCategory] = useState(''); const [selectedIds, setSelectedIds] = useState<string[]>([]); const [positionsOpen, setPositionsOpen] = useState(false); const [amount, setAmount] = useState(''); const [secondaryAmount, setSecondaryAmount] = useState(''); const [description, setDescription] = useState(''); const [eventDate, setEventDate] = useState(() => new Date().toISOString().slice(0, 10)); const [attachmentUrl, setAttachmentUrl] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  const positions = useMemo(() => priceLists.flatMap((list) => list.items.map((item) => ({ ...item, listName: list.name }))), [priceLists]); const selected = positions.filter((item) => selectedIds.includes(item.id)); const returnTo = navigationState?.returnTo ?? `/counterparties/${counterpartyId}`
  if (!user) return <Navigate to="/login" replace />
  function close() { navigate(returnTo, { replace: true }) }
  function toggle(id: string) { setSelectedIds((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]) }
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(''); try { const project = projects.find((item) => item.id === projectId); await api(`/counterparties/${counterpartyId === 'me' ? user!.id : counterpartyId}/finance-events`, { method: 'POST', body: JSON.stringify({ type: 'estimate', amount: Number(amount || 0), secondaryAmount: destination === 'project' ? Number(secondaryAmount || 0) : 0, estimateDestination: destination, expenseCategory: destination === 'company_fund' ? expenseCategory : '', estimatePositions: selected.map((item) => item.name).join(', '), projectId: destination === 'project' ? projectId : '', projectName: destination === 'project' ? project?.name ?? '' : '', description, eventDate, attachmentUrl, receiptDestination: '', tag: '', relatedPartyId: '', relatedPartyName: '', transferKind: '' }) }); close() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Не удалось сохранить смету') } finally { setSaving(false) } }
  return <main className="light-page"><div className="mobile-page estimate-page"><form className="estimate-form" onSubmit={submit}><header><button type="button" onClick={close}><X /></button><h1>Смета</h1><span /></header><div className="estimate-tabs"><button type="button" className={destination === 'project' ? 'is-active' : ''} onClick={() => setDestination('project')}>По проекту</button><button type="button" className={destination === 'company_fund' ? 'is-active' : ''} onClick={() => { setDestination('company_fund'); setProjectId('') }}>В Фонд компании</button></div>
    {destination === 'project' ? <label className="estimate-row"><Home /><span>Проект</span><select value={projectId} onChange={(event) => setProjectId(event.target.value)} required><option value="">Выберите проект</option>{projects.map((project) => <option value={project.id} key={project.id}>{project.name}</option>)}</select></label> : <><div className="estimate-row"><Home /><span>{user.organizationName}</span></div><label className="estimate-row estimate-row--category"><ListChecks /><span>Статья расходов</span><input value={expenseCategory} onChange={(event) => setExpenseCategory(event.target.value)} placeholder="Выберите или введите" list="expense-categories" required /><datalist id="expense-categories"><option value="Офисные расходы"/><option value="Реклама"/><option value="Инструменты и оборудование"/><option value="Транспорт"/><option value="Налоги и комиссии"/></datalist></label></>}
    <button className="estimate-positions-button" type="button" onClick={() => setPositionsOpen((open) => !open)}><ListChecks /><span>Позиции{selected.length ? ` (${selected.length})` : ''}</span></button>{positionsOpen && <section className="estimate-position-picker">{positions.length ? positions.map((item) => <label key={item.id}><input type="checkbox" checked={selectedIds.includes(item.id)} onChange={() => toggle(item.id)} /><span><strong>{item.name}</strong><small>{item.listName} · {item.unit}</small></span><b>{item.price.toLocaleString('ru-RU')} ₽</b></label>) : <p>Сначала добавьте позиции в прайс-лист</p>}</section>}
    {destination === 'project' ? <div className="estimate-amounts"><label><span>Сумма заказчику</span><input type="number" min="0" step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} required /></label><label><span>Сумма получателю</span><input type="number" min="0" step="0.01" value={secondaryAmount} onChange={(event) => setSecondaryAmount(event.target.value)} required /></label></div> : <label className="estimate-money"><span>Сумма</span><input type="number" min="0" step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} required /></label>}
    <label className="estimate-description"><textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Введите описание" /><input type="date" value={eventDate} onChange={(event) => setEventDate(event.target.value)} required /></label><label className="estimate-attachment"><Paperclip /><input type="url" value={attachmentUrl} onChange={(event) => setAttachmentUrl(event.target.value)} placeholder="Ссылка на фото или документ" /></label>{error && <p className="form-error">{error}</p>}<button className="primary-button" disabled={saving}>{saving ? 'Сохраняем…' : 'Сохранить'}</button>
  </form></div></main>
}
