import { ChevronRight, Copy, Pencil, Plus, Search, Trash2, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Navigate, useNavigate, useParams } from 'react-router-dom'
import { useAuth } from '../auth'
import { PageHeader } from '../components/PageHeader'
import { useExpenseArticles, type ExpenseArticle } from '../expenseArticles'
import { useProjects } from '../projects'

export function ProjectExpenseArticles() {
  const { projectId = '' } = useParams(); const navigate = useNavigate(); const { user } = useAuth(); const { projects } = useProjects(); const { articles, deleteArticle, duplicateToProject } = useExpenseArticles(); const [query, setQuery] = useState(''); const [menuOpen, setMenuOpen] = useState(false); const [duplicateOpen, setDuplicateOpen] = useState(false)
  const project = projects.find((item) => item.id === projectId); const projectArticles = useMemo(() => articles.filter((item) => item.projectId === projectId && item.name.toLowerCase().includes(query.toLowerCase())), [articles, projectId, query]); const otherArticles = articles.filter((item) => item.projectId !== projectId); const canEdit = user?.role === 'organization'
  if (!project) return <Navigate to="/projects" replace />
  function card(article: ExpenseArticle) { const editable = canEdit && !article.id.startsWith('system-'); return <article className="expense-article-card" key={article.id} onClick={() => editable && navigate(`/projects/${projectId}/expense-articles/${article.id}/edit`)}><div><strong>{article.name}</strong><span>{article.markupEnabled ? `Наценка ${article.markupPercent}%` : article.costDifferenceEnabled ? 'Разница цены и себестоимости' : 'Нет дохода'}</span></div><dl><div><dt>Расход</dt><dd>0</dd></div><div><dt>Смета</dt><dd>0</dd></div></dl>{editable && <ChevronRight />}</article> }
  return <main className="light-page"><div className="mobile-page expense-articles-page"><PageHeader title="Статьи расходов" /><p className="expense-project-name">{project.name}</p><label className="search-field"><Search /><input placeholder="Поиск" value={query} onChange={(event) => setQuery(event.target.value)} /></label><section className="expense-article-list">{projectArticles.map(card)}{card({ id: 'system-profit', projectId, name: 'Прибыль по проекту', allowPositions: false, markupEnabled: false, markupPercent: 0, markupShares: [], costDifferenceEnabled: false, costDifferenceShares: [] })}{card({ id: 'system-markup', projectId, name: 'Наценка по проекту', allowPositions: false, markupEnabled: true, markupPercent: 0, markupShares: [], costDifferenceEnabled: false, costDifferenceShares: [] })}</section>{canEdit && <button className="fab fab--page" onClick={() => setMenuOpen(true)}><Plus /></button>}{menuOpen && <div className="sheet-backdrop" onClick={() => setMenuOpen(false)}><section className="counterparty-event-sheet" onClick={(event) => event.stopPropagation()}><div className="sheet-heading"><span/><h2>Статьи расходов</h2><button className="icon-button" onClick={() => setMenuOpen(false)}><X/></button></div><button onClick={() => navigate(`/projects/${projectId}/expense-articles/new`)}><Plus/>Добавить новую</button><button onClick={() => { setMenuOpen(false); setDuplicateOpen(true) }}><Copy/>Дублировать из других проектов</button></section></div>}{duplicateOpen && <div className="sheet-backdrop" onClick={() => setDuplicateOpen(false)}><section className="expense-duplicate-sheet" onClick={(event) => event.stopPropagation()}><div className="sheet-heading"><span/><h2>Выберите статью</h2><button className="icon-button" onClick={() => setDuplicateOpen(false)}><X/></button></div>{otherArticles.length ? otherArticles.map((article) => <button key={article.id} onClick={() => { duplicateToProject(article.id, projectId); setDuplicateOpen(false) }}><Copy/><span><strong>{article.name}</strong><small>{projects.find((item) => item.id === article.projectId)?.name}</small></span></button>) : <p>В других проектах пока нет статей</p>}</section></div>}</div></main>
}
