package main

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"embed"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"golang.org/x/crypto/bcrypt"
)

//go:embed migrations/*.sql
var migrationFiles embed.FS

type app struct { db *pgxpool.Pool; secureCookie bool }
type identity struct { UserID, OrganizationID, Email, Name, OrganizationName, Role, Category string }
type financePositionInput struct { SourceItemID, Name, Unit, ExpenseArticleID string; Quantity, Cost, Price float64 }
type financeEventInput struct { Type string; Amount,SecondaryAmount float64; ProjectID,ProjectName,Description,EventDate,AttachmentURL,ReceiptDestination,Tag,RelatedPartyID,RelatedPartyName,TransferKind,EstimateDestination,ExpenseCategory,EstimatePositions string; Positions []financePositionInput }
type contextKey string
const identityKey contextKey = "identity"
const sessionCookie = "app101_session"

func main() {
	ctx := context.Background()
	db, err := pgxpool.New(ctx, env("DATABASE_URL", "postgres://app101:app101@localhost:5432/app101?sslmode=disable")); must(err)
	defer db.Close()
	for attempt := 1; ; attempt++ { err = db.Ping(ctx); if err == nil { break }; if attempt == 30 { must(err) }; time.Sleep(time.Second) }
	schema, err := migrationFiles.ReadFile("migrations/001_init.sql"); must(err)
	_, err = db.Exec(ctx, string(schema)); must(err); must(seed(ctx, db))
	a := &app{db: db, secureCookie: env("COOKIE_SECURE", "false") == "true"}
	r := chi.NewRouter(); r.Use(recoverer)
	r.Get("/healthz", func(w http.ResponseWriter, _ *http.Request) { writeJSON(w, 200, map[string]string{"status":"ok"}) })
	r.Route("/api", func(r chi.Router) {
		r.Post("/auth/login", a.login); r.Post("/auth/logout", a.logout)
		r.Get("/invitations/{token}", a.getInvitation); r.Post("/invitations/{token}/accept", a.acceptInvitation)
		r.Group(func(r chi.Router) { r.Use(a.authenticate); r.Get("/me", a.me); r.Patch("/me", a.updateMe); r.Get("/counterparties", a.listCounterparties); r.Get("/projects", a.listProjects); r.With(requireOrganization).Get("/projects/archived", a.listArchivedProjects); r.With(requireOrganization).Post("/projects/{id}/restore", a.restoreProject); r.Get("/projects/{id}/documents", a.listProjectDocuments); r.With(requireOrganization).Post("/projects/{id}/documents", a.createProjectDocument); r.With(requireOrganization).Post("/projects", a.createProject); r.With(requireOrganization).Put("/projects/{id}", a.updateProject); r.With(requireOrganization).Delete("/projects/{id}", a.deleteProject); r.Get("/price-lists", a.listPriceLists); r.With(requireOrganization).Post("/price-lists", a.createPriceList); r.With(requireOrganization).Put("/price-lists/{id}", a.updatePriceList); r.With(requireOrganization).Delete("/price-lists/{id}", a.deletePriceList); r.Get("/expense-articles", a.listExpenseArticles); r.With(requireOrganization).Post("/expense-articles", a.createExpenseArticle); r.With(requireOrganization).Put("/expense-articles/{id}", a.updateExpenseArticle); r.With(requireOrganization).Delete("/expense-articles/{id}", a.deleteExpenseArticle); r.Get("/finance-events", a.listEventHistory); r.With(requireOrganization).Get("/finance-events/deleted", a.listDeletedFinanceEvents); r.Get("/counterparties/{id}/finance-events", a.listFinanceEvents); r.With(requireOrganization).Post("/counterparties/{id}/finance-events", a.createFinanceEvent); r.With(requireOrganization).Post("/finance-events/{id}/restore", a.restoreFinanceEvent); r.With(requireOrganization).Post("/counterparties", a.createCounterparty); r.With(requireOrganization).Patch("/finance-events/{id}", a.updateFinanceEvent); r.With(requireOrganization).Delete("/finance-events/{id}", a.deleteFinanceEvent); r.With(requireOrganization).Patch("/finance-events/{id}/status", a.reviewFinanceEvent); r.With(requireOrganization).Post("/invitations", a.createInvitation) })
		r.Group(func(r chi.Router){r.Use(a.authenticate);r.Get("/document-settings",a.getDocumentSettings);r.With(requireOrganization).Put("/document-settings",a.updateDocumentSettings);r.Get("/projects/{id}/contract-settings",a.getProjectContractSettings);r.With(requireOrganization).Put("/projects/{id}/contract-settings",a.updateProjectContractSettings)})
	})
	addr := env("HTTP_ADDR", ":8080"); slog.Info("api listening", "addr", addr); must(http.ListenAndServe(addr, r))
}

func seed(ctx context.Context, db *pgxpool.Pool) error {
	if _, err := db.Exec(ctx, `UPDATE users SET email=CASE email WHEN 'demo@app101.ru' THEN 'demo@app199.ru' WHEN 'client@app101.ru' THEN 'client@app199.ru' ELSE email END WHERE email IN ('demo@app101.ru','client@app101.ru')`); err != nil { return err }
	var count int; if err := db.QueryRow(ctx, "SELECT count(*) FROM users").Scan(&count); err != nil || count > 0 { return err }
	tx, err := db.Begin(ctx); if err != nil { return err }; defer tx.Rollback(ctx)
	var orgID string; if err = tx.QueryRow(ctx, "INSERT INTO organizations(name) VALUES('КАРГОПЛАСТ') RETURNING id").Scan(&orgID); err != nil { return err }
	for _, u := range []struct{email,name,role string}{{"demo@app199.ru","Администратор","organization"},{"client@app199.ru","Клиент","client"}} {
		hash, _ := bcrypt.GenerateFromPassword([]byte("demo"), bcrypt.DefaultCost); var userID string
		if err = tx.QueryRow(ctx, "INSERT INTO users(email,name,password_hash) VALUES($1,$2,$3) RETURNING id", u.email,u.name,string(hash)).Scan(&userID); err != nil { return err }
		if _, err = tx.Exec(ctx, "INSERT INTO organization_members(organization_id,user_id,role) VALUES($1,$2,$3)", orgID,userID,u.role); err != nil { return err }
	}
	return tx.Commit(ctx)
}

func (a *app) login(w http.ResponseWriter, r *http.Request) {
	var in struct{ Email, Password string }; if !decode(w,r,&in) { return }
	var id identity; var passwordHash string
	err := a.db.QueryRow(r.Context(), `SELECT u.id,u.email,u.name,u.password_hash,o.id,o.name,m.role,COALESCE(m.category,'') FROM users u JOIN organization_members m ON m.user_id=u.id JOIN organizations o ON o.id=m.organization_id WHERE lower(u.email)=lower($1)`, strings.TrimSpace(in.Email)).Scan(&id.UserID,&id.Email,&id.Name,&passwordHash,&id.OrganizationID,&id.OrganizationName,&id.Role,&id.Category)
	if err != nil || bcrypt.CompareHashAndPassword([]byte(passwordHash), []byte(in.Password)) != nil { problem(w,401,"Неверный логин или пароль"); return }
	if err = a.newSession(r.Context(),w,id.UserID); err != nil { problem(w,500,"Не удалось создать сессию"); return }; writeJSON(w,200,userResponse(id))
}
func (a *app) logout(w http.ResponseWriter, r *http.Request) { if c,err:=r.Cookie(sessionCookie); err==nil { h:=sha256.Sum256([]byte(c.Value)); _,_=a.db.Exec(r.Context(),"DELETE FROM sessions WHERE token_hash=$1",h[:]) }; a.clearCookie(w); w.WriteHeader(204) }
func (a *app) me(w http.ResponseWriter, r *http.Request) { writeJSON(w,200,userResponse(current(r))) }
func (a *app) updateMe(w http.ResponseWriter, r *http.Request) {
	id:=current(r); var in struct{Name,Email,OrganizationName string}; if !decode(w,r,&in){return}; in.Name=strings.TrimSpace(in.Name); in.Email=strings.TrimSpace(in.Email); in.OrganizationName=strings.TrimSpace(in.OrganizationName)
	if in.Name==""||in.Email==""{problem(w,400,"Имя и email обязательны");return}
	tx,err:=a.db.Begin(r.Context());if err!=nil{problem(w,500,"Ошибка базы данных");return};defer tx.Rollback(r.Context())
	if _,err=tx.Exec(r.Context(),"UPDATE users SET name=$1,email=$2,updated_at=now() WHERE id=$3",in.Name,in.Email,id.UserID);err!=nil{problem(w,409,"Этот email уже используется");return}
	if id.Role=="organization"&&in.OrganizationName!=""{if _,err=tx.Exec(r.Context(),"UPDATE organizations SET name=$1,updated_at=now() WHERE id=$2",in.OrganizationName,id.OrganizationID);err!=nil{problem(w,500,"Не удалось обновить организацию");return};id.OrganizationName=in.OrganizationName}
	if err=tx.Commit(r.Context());err!=nil{problem(w,500,"Не удалось сохранить профиль");return};id.Name=in.Name;id.Email=in.Email;writeJSON(w,200,userResponse(id))
}

func (a *app) createInvitation(w http.ResponseWriter, r *http.Request) {
	id:=current(r);var in struct{Name,Email,Password,Category string};if !decode(w,r,&in){return};in.Name=strings.TrimSpace(in.Name);in.Email=strings.TrimSpace(in.Email)
	if in.Name==""||in.Email==""||len(in.Password)<8||!validCategory(in.Category){problem(w,400,"Проверьте имя, email, категорию и пароль");return}
	token:=randomToken();tokenHash:=sha256.Sum256([]byte(token));passwordHash,_:=bcrypt.GenerateFromPassword([]byte(in.Password),bcrypt.DefaultCost);var created,expires time.Time
	err:=a.db.QueryRow(r.Context(),`INSERT INTO invitations(organization_id,created_by,name,email,password_hash,category,token_hash,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,now()+interval '7 days') RETURNING created_at,expires_at`,id.OrganizationID,id.UserID,in.Name,in.Email,string(passwordHash),in.Category,tokenHash[:]).Scan(&created,&expires)
	if err!=nil{problem(w,500,"Не удалось создать приглашение");return};writeJSON(w,201,map[string]any{"token":token,"name":in.Name,"login":in.Email,"category":in.Category,"organizationName":id.OrganizationName,"createdAt":created,"expiresAt":expires})
}
func (a *app) getInvitation(w http.ResponseWriter,r *http.Request){
	h:=sha256.Sum256([]byte(chi.URLParam(r,"token")));var name,email,category,org string;var expires time.Time
	err:=a.db.QueryRow(r.Context(),`SELECT i.name,i.email,i.category,o.name,i.expires_at FROM invitations i JOIN organizations o ON o.id=i.organization_id WHERE i.token_hash=$1 AND i.accepted_at IS NULL AND i.revoked_at IS NULL AND i.expires_at>now()`,h[:]).Scan(&name,&email,&category,&org,&expires)
	if err!=nil{problem(w,404,"Приглашение недействительно или истекло");return};writeJSON(w,200,map[string]any{"name":name,"login":email,"category":category,"organizationName":org,"expiresAt":expires})
}
func (a *app) acceptInvitation(w http.ResponseWriter,r *http.Request){
	var in struct{Email,Password string};if !decode(w,r,&in){return};h:=sha256.Sum256([]byte(chi.URLParam(r,"token")));tx,err:=a.db.Begin(r.Context());if err!=nil{problem(w,500,"Ошибка базы данных");return};defer tx.Rollback(r.Context())
	var invitationID,orgID,name,email,passwordHash,category string;err=tx.QueryRow(r.Context(),`SELECT id,organization_id,name,email,password_hash,category FROM invitations WHERE token_hash=$1 AND accepted_at IS NULL AND revoked_at IS NULL AND expires_at>now() FOR UPDATE`,h[:]).Scan(&invitationID,&orgID,&name,&email,&passwordHash,&category)
	if err!=nil{problem(w,404,"Приглашение недействительно или истекло");return};if !strings.EqualFold(strings.TrimSpace(in.Email),email)||bcrypt.CompareHashAndPassword([]byte(passwordHash),[]byte(in.Password))!=nil{problem(w,401,"Неверный логин или временный пароль");return}
	var userID string;err=tx.QueryRow(r.Context(),"SELECT id FROM users WHERE lower(email)=lower($1)",email).Scan(&userID)
	if err==pgx.ErrNoRows{err=tx.QueryRow(r.Context(),"INSERT INTO users(email,name,password_hash) VALUES($1,$2,$3) RETURNING id",email,name,passwordHash).Scan(&userID)}
	if err!=nil{problem(w,409,"Не удалось создать пользователя");return};_,err=tx.Exec(r.Context(),`INSERT INTO organization_members(organization_id,user_id,role,category) VALUES($1,$2,'client',$3) ON CONFLICT DO NOTHING`,orgID,userID,category);if err!=nil{problem(w,500,"Не удалось назначить роль");return}
	_,err=tx.Exec(r.Context(),"UPDATE invitations SET accepted_at=now() WHERE id=$1",invitationID);if err!=nil||tx.Commit(r.Context())!=nil{problem(w,500,"Не удалось принять приглашение");return}
	if err=a.newSession(r.Context(),w,userID);err!=nil{problem(w,500,"Не удалось создать сессию");return};var id identity;if a.loadIdentity(r.Context(),userID,&id)!=nil{problem(w,500,"Не удалось загрузить профиль");return};writeJSON(w,200,userResponse(id))
}
func (a *app) createCounterparty(w http.ResponseWriter,r *http.Request){id:=current(r);var in struct{Name,Category,Phone,Email string};if !decode(w,r,&in){return};in.Name=strings.TrimSpace(in.Name);if in.Name==""||!validCategory(in.Category){problem(w,400,"Укажите имя и категорию");return};var counterpartyID string;err:=a.db.QueryRow(r.Context(),`INSERT INTO counterparties(organization_id,name,category,phone,email) VALUES($1,$2,$3,$4,$5) RETURNING id`,id.OrganizationID,in.Name,in.Category,strings.TrimSpace(in.Phone),strings.TrimSpace(in.Email)).Scan(&counterpartyID);if err!=nil{problem(w,500,"Не удалось создать контрагента");return};writeJSON(w,201,map[string]any{"id":counterpartyID,"name":in.Name,"category":in.Category,"phone":strings.TrimSpace(in.Phone),"email":strings.TrimSpace(in.Email),"invited":false})}
func (a *app) listCounterparties(w http.ResponseWriter,r *http.Request){id:=current(r);query:=`SELECT id,name,category,email,phone,false,false,created_at FROM counterparties WHERE organization_id=$1 UNION ALL SELECT id,name,category,email,'',true,(accepted_at IS NOT NULL),created_at FROM invitations WHERE organization_id=$1`;args:=[]any{id.OrganizationID};if id.Role=="client"{query=`WITH mine AS (SELECT id::text FROM invitations WHERE organization_id=$1 AND lower(email)=lower($2) AND accepted_at IS NOT NULL), visible AS (SELECT id FROM mine UNION SELECT p.customer_id FROM projects p WHERE p.organization_id=$1 AND p.archived_at IS NULL AND (p.customer_id IN(SELECT id FROM mine) OR EXISTS(SELECT 1 FROM project_participants pp WHERE pp.project_id=p.id AND pp.counterparty_id IN(SELECT id FROM mine))) UNION SELECT pp.counterparty_id FROM project_participants pp JOIN projects p ON p.id=pp.project_id WHERE p.organization_id=$1 AND p.archived_at IS NULL AND (p.customer_id IN(SELECT id FROM mine) OR EXISTS(SELECT 1 FROM project_participants own WHERE own.project_id=p.id AND own.counterparty_id IN(SELECT id FROM mine)))) SELECT id,name,category,'' AS email,phone,false,false,created_at FROM counterparties WHERE organization_id=$1 AND id::text IN(SELECT id FROM visible) UNION ALL SELECT id,name,category,CASE WHEN lower(email)=lower($2) THEN email ELSE '' END,'',true,(accepted_at IS NOT NULL),created_at FROM invitations WHERE organization_id=$1 AND id::text IN(SELECT id FROM visible)`;args=append(args,id.Email)};query+=` ORDER BY created_at DESC`;rows,err:=a.db.Query(r.Context(),query,args...);if err!=nil{problem(w,500,"Не удалось загрузить контрагентов");return};defer rows.Close();result:=[]map[string]any{};for rows.Next(){var cid,name,category,email,phone string;var invited,accepted bool;var created time.Time;_ = rows.Scan(&cid,&name,&category,&email,&phone,&invited,&accepted,&created);result=append(result,map[string]any{"id":cid,"name":name,"category":category,"email":email,"phone":phone,"invited":invited,"accepted":accepted,"createdAt":created})};writeJSON(w,200,result)}

type projectInput struct {
	ID             string          `json:"id"`
	Name           string          `json:"name"`
	ShortName      string          `json:"shortName"`
	Customer       string          `json:"customer"`
	CustomerID     string          `json:"customerId"`
	CompletionDate string          `json:"completionDate"`
	Area           float64         `json:"area"`
	Address        string          `json:"address"`
	PhotoAlbumURL  string          `json:"photoAlbumUrl"`
	AgentFeeShares json.RawMessage `json:"agentFeeShares"`
	ParticipantIDs []string        `json:"participantIds"`
}

func (a *app) listProjects(w http.ResponseWriter, r *http.Request) {
	id := current(r)
	rows, err := a.db.Query(r.Context(), `SELECT p.id,p.name,p.short_name,p.customer_name,p.customer_id,p.completion_date,p.area,p.address,p.photo_album_url,p.agent_fee_shares,COALESCE((SELECT array_agg(pp.counterparty_id ORDER BY pp.created_at) FROM project_participants pp WHERE pp.project_id=p.id),'{}'::text[]),COALESCE(fin.income,0),COALESCE(fin.expense,0),COALESCE(fin.income,0)-COALESCE(fin.expense,0) FROM projects p LEFT JOIN LATERAL(SELECT SUM(CASE WHEN l.debit_account='project:'||p.id||':accountable' THEN l.amount ELSE 0 END) income,SUM(CASE WHEN l.credit_account='project:'||p.id||':accountable' THEN l.amount ELSE 0 END) expense FROM ledger_entries l JOIN finance_events e ON e.id=l.event_id WHERE l.organization_id=p.organization_id AND e.deleted_at IS NULL AND (l.debit_account='project:'||p.id||':accountable' OR l.credit_account='project:'||p.id||':accountable')) fin ON true WHERE p.organization_id=$1 AND p.archived_at IS NULL AND ($2='organization' OR EXISTS (SELECT 1 FROM invitations mine WHERE mine.organization_id=p.organization_id AND lower(mine.email)=lower($3) AND mine.accepted_at IS NOT NULL AND (mine.id::text=p.customer_id OR EXISTS (SELECT 1 FROM project_participants pp WHERE pp.project_id=p.id AND pp.counterparty_id=mine.id::text)))) ORDER BY p.created_at`, id.OrganizationID, id.Role, id.Email)
	if err != nil { problem(w,500,"Не удалось загрузить проекты"); return }
	defer rows.Close()
	result := []map[string]any{}
	for rows.Next() {
		var projectID,name,shortName,customer,customerID,completionDate,address,photoAlbumURL string
		var area,income,expense,balance float64
		var shares json.RawMessage
		var participantIDs []string
		if err=rows.Scan(&projectID,&name,&shortName,&customer,&customerID,&completionDate,&area,&address,&photoAlbumURL,&shares,&participantIDs,&income,&expense,&balance);err!=nil{problem(w,500,"Не удалось прочитать проект");return}
		result=append(result,map[string]any{"id":projectID,"name":name,"shortName":shortName,"customer":customer,"customerId":customerID,"completionDate":completionDate,"area":area,"address":address,"photoAlbumUrl":photoAlbumURL,"agentFeeShares":shares,"participantIds":participantIDs,"balance":balance,"income":income,"expense":expense})
	}
	writeJSON(w,200,result)
}

func (a *app) createProject(w http.ResponseWriter, r *http.Request) {
	id:=current(r);var in projectInput;if !decode(w,r,&in){return};normalizeProject(&in);if in.Name==""{problem(w,400,"Название проекта обязательно");return}
	if len(in.ID)>100{problem(w,400,"Некорректный идентификатор проекта");return};if len(in.AgentFeeShares)==0{in.AgentFeeShares=json.RawMessage("[]")}
	tx,err:=a.db.Begin(r.Context());if err!=nil{problem(w,500,"Ошибка базы данных");return};defer tx.Rollback(r.Context())
	var projectID string
	if in.ID==""{err=tx.QueryRow(r.Context(),`INSERT INTO projects(organization_id,name,short_name,customer_id,customer_name,completion_date,area,address,photo_album_url,agent_fee_shares) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id`,id.OrganizationID,in.Name,in.ShortName,in.CustomerID,in.Customer,in.CompletionDate,in.Area,in.Address,in.PhotoAlbumURL,in.AgentFeeShares).Scan(&projectID)}else{projectID=in.ID;_,err=tx.Exec(r.Context(),`INSERT INTO projects(id,organization_id,name,short_name,customer_id,customer_name,completion_date,area,address,photo_album_url,agent_fee_shares) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,projectID,id.OrganizationID,in.Name,in.ShortName,in.CustomerID,in.Customer,in.CompletionDate,in.Area,in.Address,in.PhotoAlbumURL,in.AgentFeeShares)}
	if err!=nil{problem(w,409,"Проект с таким идентификатором уже существует");return};if err=replaceProjectParticipants(r.Context(),tx,projectID,in.ParticipantIDs);err!=nil{problem(w,500,"Не удалось сохранить участников");return};if err=tx.Commit(r.Context());err!=nil{problem(w,500,"Не удалось сохранить проект");return};writeJSON(w,201,map[string]string{"id":projectID})
}

func (a *app) updateProject(w http.ResponseWriter,r *http.Request){
	id:=current(r);var in projectInput;if !decode(w,r,&in){return};normalizeProject(&in);if in.Name==""{problem(w,400,"Название проекта обязательно");return};if len(in.AgentFeeShares)==0{in.AgentFeeShares=json.RawMessage("[]")}
	projectID:=chi.URLParam(r,"id");tx,err:=a.db.Begin(r.Context());if err!=nil{problem(w,500,"Ошибка базы данных");return};defer tx.Rollback(r.Context())
	result,err:=tx.Exec(r.Context(),`UPDATE projects SET name=$1,short_name=$2,customer_id=$3,customer_name=$4,completion_date=$5,area=$6,address=$7,photo_album_url=$8,agent_fee_shares=$9,updated_at=now() WHERE id=$10 AND organization_id=$11 AND archived_at IS NULL`,in.Name,in.ShortName,in.CustomerID,in.Customer,in.CompletionDate,in.Area,in.Address,in.PhotoAlbumURL,in.AgentFeeShares,projectID,id.OrganizationID);if err!=nil{problem(w,400,"Не удалось изменить проект");return};if result.RowsAffected()==0{problem(w,404,"Проект не найден");return};if err=replaceProjectParticipants(r.Context(),tx,projectID,in.ParticipantIDs);err!=nil{problem(w,500,"Не удалось сохранить участников");return};if err=tx.Commit(r.Context());err!=nil{problem(w,500,"Не удалось изменить проект");return};writeJSON(w,200,map[string]string{"id":projectID})
}

func (a *app) deleteProject(w http.ResponseWriter,r *http.Request){id:=current(r);result,err:=a.db.Exec(r.Context(),`UPDATE projects SET archived_at=now(),updated_at=now() WHERE id=$1 AND organization_id=$2 AND archived_at IS NULL`,chi.URLParam(r,"id"),id.OrganizationID);if err!=nil{problem(w,500,"Не удалось архивировать проект");return};if result.RowsAffected()==0{problem(w,404,"Проект не найден");return};w.WriteHeader(http.StatusNoContent)}
func (a *app) listArchivedProjects(w http.ResponseWriter,r *http.Request){id:=current(r);rows,err:=a.db.Query(r.Context(),`SELECT id,name,customer_name,archived_at FROM projects WHERE organization_id=$1 AND archived_at IS NOT NULL ORDER BY archived_at DESC LIMIT 500`,id.OrganizationID);if err!=nil{problem(w,500,"Не удалось загрузить архив проектов");return};defer rows.Close();result:=[]map[string]any{};for rows.Next(){var projectID,name,customer string;var archivedAt time.Time;if rows.Scan(&projectID,&name,&customer,&archivedAt)!=nil{problem(w,500,"Не удалось прочитать архив проекта");return};result=append(result,map[string]any{"id":projectID,"name":name,"customer":customer,"archivedAt":archivedAt})};writeJSON(w,200,result)}
func (a *app) restoreProject(w http.ResponseWriter,r *http.Request){id:=current(r);result,err:=a.db.Exec(r.Context(),`UPDATE projects SET archived_at=NULL,updated_at=now() WHERE id=$1 AND organization_id=$2 AND archived_at IS NOT NULL`,chi.URLParam(r,"id"),id.OrganizationID);if err!=nil{problem(w,500,"Не удалось восстановить проект");return};if result.RowsAffected()==0{problem(w,404,"Архивный проект не найден");return};writeJSON(w,200,map[string]string{"id":chi.URLParam(r,"id")})}
func (a *app) listProjectDocuments(w http.ResponseWriter,r *http.Request){id:=current(r);projectID:=chi.URLParam(r,"id");var allowed bool;if id.Role=="organization"{_ = a.db.QueryRow(r.Context(),`SELECT EXISTS(SELECT 1 FROM projects WHERE id=$1 AND organization_id=$2)`,projectID,id.OrganizationID).Scan(&allowed)}else{_ = a.db.QueryRow(r.Context(),`SELECT EXISTS(SELECT 1 FROM projects p JOIN invitations mine ON mine.organization_id=p.organization_id AND lower(mine.email)=lower($3) AND mine.accepted_at IS NOT NULL WHERE p.id=$1 AND p.organization_id=$2 AND (p.customer_id=mine.id::text OR EXISTS(SELECT 1 FROM project_participants pp WHERE pp.project_id=p.id AND pp.counterparty_id=mine.id::text)))`,projectID,id.OrganizationID,id.Email).Scan(&allowed)};if !allowed{problem(w,403,"Недостаточно прав");return};rows,err:=a.db.Query(r.Context(),`SELECT d.id,d.document_type,d.title,d.file_name,d.snapshot,d.created_at,u.name FROM project_documents d JOIN users u ON u.id=d.created_by WHERE d.organization_id=$1 AND d.project_id=$2 ORDER BY d.created_at DESC LIMIT 200`,id.OrganizationID,projectID);if err!=nil{problem(w,500,"Не удалось загрузить документы");return};defer rows.Close();result:=[]map[string]any{};for rows.Next(){var documentID,documentType,title,fileName,creator string;var snapshot json.RawMessage;var createdAt time.Time;if rows.Scan(&documentID,&documentType,&title,&fileName,&snapshot,&createdAt,&creator)!=nil{problem(w,500,"Не удалось прочитать документ");return};result=append(result,map[string]any{"id":documentID,"type":documentType,"title":title,"fileName":fileName,"snapshot":snapshot,"createdAt":createdAt,"createdBy":creator})};writeJSON(w,200,result)}
func (a *app) createProjectDocument(w http.ResponseWriter,r *http.Request){id:=current(r);projectID:=chi.URLParam(r,"id");var in struct{Type,Title,FileName string;Snapshot json.RawMessage};if !decode(w,r,&in){return};if !validDocumentType(in.Type)||strings.TrimSpace(in.Title)==""||strings.TrimSpace(in.FileName)==""||len(in.Snapshot)==0{problem(w,400,"Некорректные данные документа");return};var documentID string;err:=a.db.QueryRow(r.Context(),`INSERT INTO project_documents(organization_id,project_id,document_type,title,file_name,snapshot,created_by) SELECT $1,id,$3,$4,$5,$6,$7 FROM projects WHERE id=$2 AND organization_id=$1 AND archived_at IS NULL RETURNING id`,id.OrganizationID,projectID,in.Type,strings.TrimSpace(in.Title),strings.TrimSpace(in.FileName),in.Snapshot,id.UserID).Scan(&documentID);if err!=nil{problem(w,400,"Не удалось сохранить версию документа");return};writeJSON(w,201,map[string]string{"id":documentID})}
func (a *app) getDocumentSettings(w http.ResponseWriter,r *http.Request){id:=current(r);var data json.RawMessage;err:=a.db.QueryRow(r.Context(),`SELECT data FROM organization_document_settings WHERE organization_id=$1`,id.OrganizationID).Scan(&data);if err==pgx.ErrNoRows{writeJSON(w,200,map[string]any{});return};if err!=nil{problem(w,500,"Не удалось загрузить реквизиты");return};writeJSON(w,200,data)}
func (a *app) updateDocumentSettings(w http.ResponseWriter,r *http.Request){id:=current(r);var data json.RawMessage;if !decode(w,r,&data){return};if len(data)==0{problem(w,400,"Некорректные реквизиты");return};_,err:=a.db.Exec(r.Context(),`INSERT INTO organization_document_settings(organization_id,data) VALUES($1,$2) ON CONFLICT(organization_id) DO UPDATE SET data=excluded.data,updated_at=now()`,id.OrganizationID,data);if err!=nil{problem(w,500,"Не удалось сохранить реквизиты");return};writeJSON(w,200,data)}
func (a *app) getProjectContractSettings(w http.ResponseWriter,r *http.Request){id:=current(r);projectID:=chi.URLParam(r,"id");var allowed bool;if id.Role=="organization"{_ = a.db.QueryRow(r.Context(),`SELECT EXISTS(SELECT 1 FROM projects WHERE id=$1 AND organization_id=$2)`,projectID,id.OrganizationID).Scan(&allowed)}else{_ = a.db.QueryRow(r.Context(),`SELECT EXISTS(SELECT 1 FROM projects p JOIN invitations mine ON mine.organization_id=p.organization_id AND lower(mine.email)=lower($3) AND mine.accepted_at IS NOT NULL WHERE p.id=$1 AND p.organization_id=$2 AND (p.customer_id=mine.id::text OR EXISTS(SELECT 1 FROM project_participants pp WHERE pp.project_id=p.id AND pp.counterparty_id=mine.id::text)))`,projectID,id.OrganizationID,id.Email).Scan(&allowed)};if !allowed{problem(w,403,"Недостаточно прав");return};var data json.RawMessage;err:=a.db.QueryRow(r.Context(),`SELECT data FROM project_contract_settings WHERE project_id=$1 AND organization_id=$2`,projectID,id.OrganizationID).Scan(&data);if err==pgx.ErrNoRows{writeJSON(w,200,map[string]any{});return};if err!=nil{problem(w,500,"Не удалось загрузить параметры договора");return};writeJSON(w,200,data)}
func (a *app) updateProjectContractSettings(w http.ResponseWriter,r *http.Request){id:=current(r);projectID:=chi.URLParam(r,"id");var data json.RawMessage;if !decode(w,r,&data){return};result,err:=a.db.Exec(r.Context(),`INSERT INTO project_contract_settings(project_id,organization_id,data) SELECT id,$2,$3 FROM projects WHERE id=$1 AND organization_id=$2 AND archived_at IS NULL ON CONFLICT(project_id) DO UPDATE SET data=excluded.data,updated_at=now()`,projectID,id.OrganizationID,data);if err!=nil{problem(w,500,"Не удалось сохранить договор");return};if result.RowsAffected()==0{problem(w,404,"Проект не найден");return};writeJSON(w,200,data)}
func normalizeProject(in *projectInput){in.Name=strings.TrimSpace(in.Name);in.ShortName=strings.TrimSpace(in.ShortName);in.Customer=strings.TrimSpace(in.Customer);in.CustomerID=strings.TrimSpace(in.CustomerID);in.CompletionDate=strings.TrimSpace(in.CompletionDate);in.Address=strings.TrimSpace(in.Address);in.PhotoAlbumURL=strings.TrimSpace(in.PhotoAlbumURL);if in.Area<0{in.Area=0}}
func replaceProjectParticipants(ctx context.Context,tx pgx.Tx,projectID string,participantIDs []string)error{if _,err:=tx.Exec(ctx,"DELETE FROM project_participants WHERE project_id=$1",projectID);err!=nil{return err};seen:=map[string]bool{};for _,participantID:=range participantIDs{participantID=strings.TrimSpace(participantID);if participantID==""||seen[participantID]{continue};seen[participantID]=true;if _,err:=tx.Exec(ctx,"INSERT INTO project_participants(project_id,counterparty_id) VALUES($1,$2)",projectID,participantID);err!=nil{return err}};return nil}

func (a *app) listPriceLists(w http.ResponseWriter,r *http.Request){id:=current(r);rows,err:=a.db.Query(r.Context(),`SELECT data FROM price_lists WHERE organization_id=$1 AND archived_at IS NULL ORDER BY created_at`,id.OrganizationID);if err!=nil{problem(w,500,"Не удалось загрузить прайс-листы");return};defer rows.Close();result:=[]json.RawMessage{};for rows.Next(){var data json.RawMessage;if err=rows.Scan(&data);err!=nil{problem(w,500,"Не удалось прочитать прайс-лист");return};if id.Role=="client"{data=redactPriceList(data,id.Category)};result=append(result,data)};writeJSON(w,200,result)}
func (a *app) createPriceList(w http.ResponseWriter,r *http.Request){id:=current(r);raw,document,ok:=decodeDocument(w,r);if !ok{return};listID,name:=documentString(document,"id"),documentString(document,"name");if listID==""||name==""{problem(w,400,"Идентификатор и название прайс-листа обязательны");return};_,err:=a.db.Exec(r.Context(),`INSERT INTO price_lists(id,organization_id,name,data) VALUES($1,$2,$3,$4)`,listID,id.OrganizationID,name,raw);if err!=nil{problem(w,409,"Прайс-лист уже существует");return};writeJSON(w,201,map[string]string{"id":listID})}
func (a *app) updatePriceList(w http.ResponseWriter,r *http.Request){id:=current(r);raw,document,ok:=decodeDocument(w,r);if !ok{return};name:=documentString(document,"name");if name==""{problem(w,400,"Название прайс-листа обязательно");return};result,err:=a.db.Exec(r.Context(),`UPDATE price_lists SET name=$1,data=$2,updated_at=now() WHERE id=$3 AND organization_id=$4 AND archived_at IS NULL`,name,raw,chi.URLParam(r,"id"),id.OrganizationID);if err!=nil{problem(w,400,"Не удалось изменить прайс-лист");return};if result.RowsAffected()==0{problem(w,404,"Прайс-лист не найден");return};writeJSON(w,200,map[string]string{"id":chi.URLParam(r,"id")})}
func (a *app) deletePriceList(w http.ResponseWriter,r *http.Request){id:=current(r);result,err:=a.db.Exec(r.Context(),`UPDATE price_lists SET archived_at=now(),updated_at=now() WHERE id=$1 AND organization_id=$2 AND archived_at IS NULL`,chi.URLParam(r,"id"),id.OrganizationID);if err!=nil{problem(w,500,"Не удалось архивировать прайс-лист");return};if result.RowsAffected()==0{problem(w,404,"Прайс-лист не найден");return};w.WriteHeader(http.StatusNoContent)}

func (a *app) listExpenseArticles(w http.ResponseWriter,r *http.Request){id:=current(r);query:=`SELECT a.data FROM expense_articles a JOIN projects p ON p.id=a.project_id WHERE a.organization_id=$1 AND a.archived_at IS NULL AND p.archived_at IS NULL`;args:=[]any{id.OrganizationID};if id.Role=="client"{query+=` AND EXISTS(SELECT 1 FROM invitations mine WHERE mine.organization_id=p.organization_id AND lower(mine.email)=lower($2) AND mine.accepted_at IS NOT NULL AND (mine.id::text=p.customer_id OR EXISTS(SELECT 1 FROM project_participants pp WHERE pp.project_id=p.id AND pp.counterparty_id=mine.id::text)))`;args=append(args,id.Email)};query+=` ORDER BY a.created_at`;rows,err:=a.db.Query(r.Context(),query,args...);if err!=nil{problem(w,500,"Не удалось загрузить статьи расходов");return};defer rows.Close();result:=[]json.RawMessage{};for rows.Next(){var data json.RawMessage;if err=rows.Scan(&data);err!=nil{problem(w,500,"Не удалось прочитать статью расходов");return};result=append(result,data)};writeJSON(w,200,result)}
func (a *app) createExpenseArticle(w http.ResponseWriter,r *http.Request){id:=current(r);raw,document,ok:=decodeDocument(w,r);if !ok{return};articleID,name,projectID:=documentString(document,"id"),documentString(document,"name"),documentString(document,"projectId");if articleID==""||name==""||projectID==""{problem(w,400,"Проект, идентификатор и название статьи обязательны");return};var allowed bool;_ = a.db.QueryRow(r.Context(),`SELECT EXISTS(SELECT 1 FROM projects WHERE id=$1 AND organization_id=$2 AND archived_at IS NULL)`,projectID,id.OrganizationID).Scan(&allowed);if !allowed{problem(w,404,"Проект не найден");return};_,err:=a.db.Exec(r.Context(),`INSERT INTO expense_articles(id,organization_id,project_id,name,data) VALUES($1,$2,$3,$4,$5)`,articleID,id.OrganizationID,projectID,name,raw);if err!=nil{problem(w,409,"Статья расходов уже существует");return};writeJSON(w,201,map[string]string{"id":articleID})}
func (a *app) updateExpenseArticle(w http.ResponseWriter,r *http.Request){id:=current(r);raw,document,ok:=decodeDocument(w,r);if !ok{return};name,projectID:=documentString(document,"name"),documentString(document,"projectId");if name==""||projectID==""{problem(w,400,"Проект и название статьи обязательны");return};result,err:=a.db.Exec(r.Context(),`UPDATE expense_articles SET project_id=$1,name=$2,data=$3,updated_at=now() WHERE id=$4 AND organization_id=$5 AND archived_at IS NULL`,projectID,name,raw,chi.URLParam(r,"id"),id.OrganizationID);if err!=nil{problem(w,400,"Не удалось изменить статью расходов");return};if result.RowsAffected()==0{problem(w,404,"Статья расходов не найдена");return};writeJSON(w,200,map[string]string{"id":chi.URLParam(r,"id")})}
func (a *app) deleteExpenseArticle(w http.ResponseWriter,r *http.Request){id:=current(r);result,err:=a.db.Exec(r.Context(),`UPDATE expense_articles SET archived_at=now(),updated_at=now() WHERE id=$1 AND organization_id=$2 AND archived_at IS NULL`,chi.URLParam(r,"id"),id.OrganizationID);if err!=nil{problem(w,500,"Не удалось архивировать статью расходов");return};if result.RowsAffected()==0{problem(w,404,"Статья расходов не найдена");return};w.WriteHeader(http.StatusNoContent)}
func decodeDocument(w http.ResponseWriter,r *http.Request)(json.RawMessage,map[string]any,bool){var raw json.RawMessage;if !decode(w,r,&raw){return nil,nil,false};var document map[string]any;if json.Unmarshal(raw,&document)!=nil{problem(w,400,"Некорректный документ");return nil,nil,false};return raw,document,true}
func documentString(document map[string]any,key string)string{value,_:=document[key].(string);return strings.TrimSpace(value)}
func redactPriceList(raw json.RawMessage,category string)json.RawMessage{var document map[string]any;if json.Unmarshal(raw,&document)!=nil{return raw};items,_:=document["items"].([]any);for _,value:=range items{item,_:=value.(map[string]any);if category=="partner"{continue};if category=="contractor"||category=="supplier"||category=="employee"{delete(item,"price")}else{delete(item,"cost")}};result,err:=json.Marshal(document);if err!=nil{return raw};return result}

func (a *app) createFinanceEvent(w http.ResponseWriter,r *http.Request){
	id:=current(r);counterpartyID:=chi.URLParam(r,"id");var in financeEventInput;if !decode(w,r,&in){return}
	if !validFinanceType(in.Type)||in.Amount<0{problem(w,400,"Проверьте тип операции и сумму");return};if in.EventDate==""{in.EventDate=time.Now().Format("2006-01-02")};if in.ReceiptDestination==""{in.ReceiptDestination="project"}
	if in.Type=="receipt"&&!validReceiptDestination(in.ReceiptDestination){problem(w,400,"Выберите раздел поступления");return};if in.Type=="receipt"&&in.ReceiptDestination=="project"&&strings.TrimSpace(in.ProjectID)==""{problem(w,400,"Для поступления по проекту выберите проект");return};if in.Type!="receipt"{in.ReceiptDestination=""}
	if in.Type=="receipt"&&in.ReceiptDestination!="company_fund"&&strings.TrimSpace(in.RelatedPartyID)==""{problem(w,400,"Выберите заказчика или плательщика");return};if in.Type=="transfer"&&(!validTransferKind(in.TransferKind)||strings.TrimSpace(in.RelatedPartyID)==""){problem(w,400,"Выберите тип перевода и получателя");return};if in.Type!="receipt"&&in.Type!="transfer"||in.Type=="receipt"&&in.ReceiptDestination=="company_fund"{in.RelatedPartyID="";in.RelatedPartyName=""};if in.Type!="transfer"{in.TransferKind=""}
	if in.Type=="estimate" { if in.EstimateDestination!="project"&&in.EstimateDestination!="company_fund" { problem(w,400,"Выберите раздел сметы");return }; if in.EstimateDestination=="project"&&strings.TrimSpace(in.ProjectID)=="" { problem(w,400,"Выберите проект");return }; if in.EstimateDestination=="company_fund" { in.ProjectID="";in.ProjectName="" } } else { in.EstimateDestination="";in.SecondaryAmount=0;in.ExpenseCategory="";in.EstimatePositions="" }
	tx,err:=a.db.Begin(r.Context());if err!=nil{problem(w,500,"Ошибка базы данных");return};defer tx.Rollback(r.Context());var eventID string;err=tx.QueryRow(r.Context(),`INSERT INTO finance_events(organization_id,counterparty_id,event_type,amount,project_id,project_name,description,event_date,attachment_url,receipt_destination,tag,related_party_id,related_party_name,transfer_kind,estimate_destination,secondary_amount,expense_category,estimate_positions,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19) RETURNING id`,id.OrganizationID,counterpartyID,in.Type,in.Amount,in.ProjectID,strings.TrimSpace(in.ProjectName),strings.TrimSpace(in.Description),in.EventDate,strings.TrimSpace(in.AttachmentURL),in.ReceiptDestination,strings.TrimSpace(in.Tag),strings.TrimSpace(in.RelatedPartyID),strings.TrimSpace(in.RelatedPartyName),in.TransferKind,in.EstimateDestination,in.SecondaryAmount,strings.TrimSpace(in.ExpenseCategory),strings.TrimSpace(in.EstimatePositions),id.UserID).Scan(&eventID)
	if err!=nil||replaceFinancePositions(r.Context(),tx,eventID,in.Positions)!=nil||tx.Commit(r.Context())!=nil{problem(w,400,"Не удалось создать финансовое событие");return};writeJSON(w,201,map[string]string{"id":eventID})
}
func replaceFinancePositions(ctx context.Context,tx pgx.Tx,eventID string,positions []financePositionInput)error{if _,err:=tx.Exec(ctx,"DELETE FROM finance_event_positions WHERE event_id=$1",eventID);err!=nil{return err};for index,position:=range positions{position.Name=strings.TrimSpace(position.Name);position.Unit=strings.TrimSpace(position.Unit);if position.Name==""||position.Quantity<0||position.Cost<0||position.Price<0{return fmt.Errorf("invalid finance position")};if position.Quantity==0{position.Quantity=1};if _,err:=tx.Exec(ctx,`INSERT INTO finance_event_positions(event_id,source_item_id,name,unit,quantity,cost,price,expense_article_id,sort_order) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,eventID,strings.TrimSpace(position.SourceItemID),position.Name,position.Unit,position.Quantity,position.Cost,position.Price,strings.TrimSpace(position.ExpenseArticleID),index);err!=nil{return err}};return nil}
func replaceLedgerEntry(ctx context.Context,tx pgx.Tx,eventID string)error{if _,err:=tx.Exec(ctx,"DELETE FROM ledger_entries WHERE event_id=$1",eventID);err!=nil{return err};var organizationID,counterpartyID,eventType,status,projectID,receiptDestination,relatedPartyID,transferKind string;var amount float64;var deletedAt *time.Time;if err:=tx.QueryRow(ctx,`SELECT organization_id,counterparty_id,event_type,status,project_id,receipt_destination,related_party_id,transfer_kind,amount,deleted_at FROM finance_events WHERE id=$1`,eventID).Scan(&organizationID,&counterpartyID,&eventType,&status,&projectID,&receiptDestination,&relatedPartyID,&transferKind,&amount,&deletedAt);err!=nil{return err};if status!="confirmed"||deletedAt!=nil||eventType=="estimate"||amount<=0{return nil};debit,credit:="","";switch eventType{case"receipt":credit="external:income";switch receiptDestination{case"agent_fee":debit="counterparty:"+counterpartyID+":own";case"company_fund":debit="fund:accountable";default:debit="project:"+projectID+":accountable"};case"report":debit="external:expense";if projectID!=""{credit="project:"+projectID+":accountable"}else{credit="fund:accountable"};case"transfer":switch transferKind{case"project_to_fund":debit,credit="fund:accountable","project:"+projectID+":accountable";case"fund_to_project":debit,credit="project:"+projectID+":accountable","fund:accountable";case"project_payment":debit,credit="counterparty:"+relatedPartyID+":own","project:"+projectID+":accountable";case"project_accountable":debit,credit="counterparty:"+relatedPartyID+":accountable","project:"+projectID+":accountable";case"fund_payment":debit,credit="counterparty:"+relatedPartyID+":own","fund:accountable"}};if debit==""||credit==""{return fmt.Errorf("invalid ledger mapping")};_,err:=tx.Exec(ctx,`INSERT INTO ledger_entries(organization_id,event_id,debit_account,credit_account,amount) VALUES($1,$2,$3,$4,$5)`,organizationID,eventID,debit,credit,amount);return err}
func (a *app) financePositions(ctx context.Context,eventID string)[]map[string]any{rows,err:=a.db.Query(ctx,`SELECT source_item_id,name,unit,quantity,cost,price,expense_article_id FROM finance_event_positions WHERE event_id=$1 ORDER BY sort_order,id`,eventID);if err!=nil{return []map[string]any{}};defer rows.Close();result:=[]map[string]any{};for rows.Next(){var sourceItemID,name,unit,expenseArticleID string;var quantity,cost,price float64;if rows.Scan(&sourceItemID,&name,&unit,&quantity,&cost,&price,&expenseArticleID)!=nil{return []map[string]any{}};result=append(result,map[string]any{"sourceItemId":sourceItemID,"name":name,"unit":unit,"quantity":quantity,"cost":cost,"price":price,"expenseArticleId":expenseArticleID})};return result}
func (a *app) listFinanceEvents(w http.ResponseWriter,r *http.Request){
	id:=current(r);counterpartyID:=chi.URLParam(r,"id");if id.Role=="client"{var allowed bool;_ = a.db.QueryRow(r.Context(),`SELECT EXISTS(SELECT 1 FROM invitations WHERE id=$1 AND organization_id=$2 AND lower(email)=lower($3) AND accepted_at IS NOT NULL)`,counterpartyID,id.OrganizationID,id.Email).Scan(&allowed);if !allowed{problem(w,403,"Недостаточно прав");return}}
	rows,err:=a.db.Query(r.Context(),`SELECT e.id,e.event_type,e.amount,e.status,e.project_id,e.project_name,e.description,e.event_date,e.attachment_url,e.receipt_destination,e.tag,e.related_party_id,e.related_party_name,e.transfer_kind,e.estimate_destination,e.secondary_amount,e.expense_category,e.estimate_positions,e.created_at,u.name FROM finance_events e JOIN users u ON u.id=e.created_by WHERE e.organization_id=$1 AND e.counterparty_id=$2 AND e.deleted_at IS NULL ORDER BY e.created_at DESC`,id.OrganizationID,counterpartyID);if err!=nil{problem(w,400,"Не удалось загрузить события");return};defer rows.Close()
	events:=[]map[string]any{};var balance,received,spent float64;for rows.Next(){var eventID,eventType,status,projectID,projectName,description,attachmentURL,receiptDestination,tag,relatedPartyID,relatedPartyName,transferKind,estimateDestination,expenseCategory,estimatePositions,creator string;var amount,secondaryAmount float64;var eventDate,created time.Time;if err=rows.Scan(&eventID,&eventType,&amount,&status,&projectID,&projectName,&description,&eventDate,&attachmentURL,&receiptDestination,&tag,&relatedPartyID,&relatedPartyName,&transferKind,&estimateDestination,&secondaryAmount,&expenseCategory,&estimatePositions,&created,&creator);err!=nil{problem(w,500,"Не удалось прочитать финансовое событие");return};events=append(events,map[string]any{"id":eventID,"type":eventType,"amount":amount,"status":status,"projectId":projectID,"projectName":projectName,"description":description,"eventDate":eventDate.Format("2006-01-02"),"attachmentUrl":attachmentURL,"receiptDestination":receiptDestination,"tag":tag,"relatedPartyId":relatedPartyID,"relatedPartyName":relatedPartyName,"transferKind":transferKind,"estimateDestination":estimateDestination,"secondaryAmount":secondaryAmount,"expenseCategory":expenseCategory,"estimatePositions":estimatePositions,"positions":a.financePositions(r.Context(),eventID),"createdAt":created,"createdBy":creator});if status=="confirmed"{switch eventType{case"receipt":received+=amount;balance+=amount;case"report","transfer":spent+=amount;balance-=amount}}};writeJSON(w,200,map[string]any{"events":events,"balance":balance,"received":received,"spent":spent})
}
func (a *app) listEventHistory(w http.ResponseWriter,r *http.Request){
	id:=current(r);query:=`SELECT e.id,e.counterparty_id,COALESCE(c.name,i.name,owner.name,'Контрагент'),e.event_type,e.amount,e.status,e.project_id,e.project_name,e.description,e.event_date,e.attachment_url,e.receipt_destination,e.tag,e.related_party_id,e.related_party_name,e.transfer_kind,e.estimate_destination,e.secondary_amount,e.expense_category,e.estimate_positions,e.created_at,u.name FROM finance_events e JOIN users u ON u.id=e.created_by LEFT JOIN counterparties c ON c.id=e.counterparty_id LEFT JOIN invitations i ON i.id=e.counterparty_id LEFT JOIN users owner ON owner.id=e.counterparty_id WHERE e.organization_id=$1 AND e.deleted_at IS NULL AND e.event_date>=current_date-interval '3 years'`
	args:=[]any{id.OrganizationID};if id.Role=="client"{query+=` AND EXISTS(SELECT 1 FROM invitations mine WHERE mine.organization_id=e.organization_id AND lower(mine.email)=lower($2) AND mine.accepted_at IS NOT NULL AND (mine.id=e.counterparty_id OR EXISTS(SELECT 1 FROM projects p WHERE p.id=e.project_id AND p.archived_at IS NULL AND (p.customer_id=mine.id::text OR EXISTS(SELECT 1 FROM project_participants pp WHERE pp.project_id=p.id AND pp.counterparty_id=mine.id::text)))))`;args=append(args,id.Email)};query+=` ORDER BY e.event_date DESC,e.created_at DESC LIMIT 5000`
	rows,err:=a.db.Query(r.Context(),query,args...);if err!=nil{problem(w,500,"Не удалось загрузить историю");return};defer rows.Close();events:=[]map[string]any{}
	for rows.Next(){var eventID,counterpartyID,counterpartyName,eventType,status,projectID,projectName,description,attachmentURL,receiptDestination,tag,relatedPartyID,relatedPartyName,transferKind,estimateDestination,expenseCategory,estimatePositions,creator string;var amount,secondaryAmount float64;var eventDate,created time.Time;if err=rows.Scan(&eventID,&counterpartyID,&counterpartyName,&eventType,&amount,&status,&projectID,&projectName,&description,&eventDate,&attachmentURL,&receiptDestination,&tag,&relatedPartyID,&relatedPartyName,&transferKind,&estimateDestination,&secondaryAmount,&expenseCategory,&estimatePositions,&created,&creator);err!=nil{problem(w,500,"Не удалось прочитать историю");return};events=append(events,map[string]any{"id":eventID,"counterpartyId":counterpartyID,"counterpartyName":counterpartyName,"type":eventType,"amount":amount,"status":status,"projectId":projectID,"projectName":projectName,"description":description,"eventDate":eventDate.Format("2006-01-02"),"attachmentUrl":attachmentURL,"receiptDestination":receiptDestination,"tag":tag,"relatedPartyId":relatedPartyID,"relatedPartyName":relatedPartyName,"transferKind":transferKind,"estimateDestination":estimateDestination,"secondaryAmount":secondaryAmount,"expenseCategory":expenseCategory,"estimatePositions":estimatePositions,"positions":a.financePositions(r.Context(),eventID),"createdAt":created,"createdBy":creator})};writeJSON(w,200,map[string]any{"events":events,"retentionMonths":36,"limit":5000})
}
func (a *app) updateFinanceEvent(w http.ResponseWriter,r *http.Request){
	id:=current(r);eventID:=chi.URLParam(r,"id");var in financeEventInput;if !decode(w,r,&in){return}
	if !validFinanceType(in.Type)||in.Amount<0{problem(w,400,"Проверьте тип операции и сумму");return};if in.EventDate==""{problem(w,400,"Укажите дату");return};if in.Type=="receipt"&&!validReceiptDestination(in.ReceiptDestination){problem(w,400,"Выберите раздел поступления");return};if in.Type=="receipt"&&in.ReceiptDestination=="project"&&strings.TrimSpace(in.ProjectID)==""{problem(w,400,"Выберите проект");return};if in.Type=="receipt"&&in.ReceiptDestination!="company_fund"&&strings.TrimSpace(in.RelatedPartyID)==""{problem(w,400,"Выберите заказчика или плательщика");return};if in.Type=="transfer"&&(!validTransferKind(in.TransferKind)||strings.TrimSpace(in.RelatedPartyID)==""){problem(w,400,"Выберите тип перевода и получателя");return};if in.Type!="receipt"{in.ReceiptDestination=""};if in.Type!="receipt"&&in.Type!="transfer"||in.Type=="receipt"&&in.ReceiptDestination=="company_fund"{in.RelatedPartyID="";in.RelatedPartyName=""};if in.Type!="transfer"{in.TransferKind=""}
	if in.Type=="estimate"{if in.EstimateDestination!="project"&&in.EstimateDestination!="company_fund"{problem(w,400,"Выберите раздел сметы");return};if in.EstimateDestination=="project"&&strings.TrimSpace(in.ProjectID)==""{problem(w,400,"Выберите проект");return};if in.EstimateDestination=="company_fund"{in.ProjectID="";in.ProjectName=""}}else{in.EstimateDestination="";in.SecondaryAmount=0;in.ExpenseCategory="";in.EstimatePositions="";in.Positions=nil}
	tx,err:=a.db.Begin(r.Context());if err!=nil{problem(w,500,"Ошибка базы данных");return};defer tx.Rollback(r.Context());if _,err=tx.Exec(r.Context(),`INSERT INTO finance_event_audit(event_id,organization_id,action,snapshot,actor_id) SELECT id,organization_id,'updated',to_jsonb(finance_events),$3 FROM finance_events WHERE id=$1 AND organization_id=$2 AND deleted_at IS NULL`,eventID,id.OrganizationID,id.UserID);err!=nil{problem(w,500,"Не удалось записать аудит");return}
	result,err:=tx.Exec(r.Context(),`UPDATE finance_events SET event_type=$1,amount=$2,project_id=$3,project_name=$4,description=$5,event_date=$6,attachment_url=$7,receipt_destination=$8,tag=$9,related_party_id=$10,related_party_name=$11,transfer_kind=$12,estimate_destination=$13,secondary_amount=$14,expense_category=$15,estimate_positions=$16,updated_at=now() WHERE id=$17 AND organization_id=$18 AND deleted_at IS NULL`,in.Type,in.Amount,in.ProjectID,strings.TrimSpace(in.ProjectName),strings.TrimSpace(in.Description),in.EventDate,strings.TrimSpace(in.AttachmentURL),in.ReceiptDestination,strings.TrimSpace(in.Tag),strings.TrimSpace(in.RelatedPartyID),strings.TrimSpace(in.RelatedPartyName),in.TransferKind,in.EstimateDestination,in.SecondaryAmount,strings.TrimSpace(in.ExpenseCategory),strings.TrimSpace(in.EstimatePositions),eventID,id.OrganizationID);if err!=nil{problem(w,400,"Не удалось изменить событие");return};if result.RowsAffected()==0{problem(w,404,"Событие не найдено");return};if err=replaceFinancePositions(r.Context(),tx,eventID,in.Positions);err!=nil{problem(w,400,"Не удалось изменить позиции события");return};if err=replaceLedgerEntry(r.Context(),tx,eventID);err!=nil||tx.Commit(r.Context())!=nil{problem(w,400,"Не удалось пересчитать проводку");return};writeJSON(w,200,map[string]string{"id":eventID})
}
func (a *app) deleteFinanceEvent(w http.ResponseWriter,r *http.Request){id:=current(r);eventID:=chi.URLParam(r,"id");tx,err:=a.db.Begin(r.Context());if err!=nil{problem(w,500,"Ошибка базы данных");return};defer tx.Rollback(r.Context());if _,err=tx.Exec(r.Context(),`INSERT INTO finance_event_audit(event_id,organization_id,action,snapshot,actor_id) SELECT id,organization_id,'deleted',to_jsonb(finance_events),$3 FROM finance_events WHERE id=$1 AND organization_id=$2 AND deleted_at IS NULL`,eventID,id.OrganizationID,id.UserID);err!=nil{problem(w,500,"Не удалось записать аудит");return};result,err:=tx.Exec(r.Context(),`UPDATE finance_events SET deleted_at=now(),deleted_by=$3,updated_at=now() WHERE id=$1 AND organization_id=$2 AND deleted_at IS NULL`,eventID,id.OrganizationID,id.UserID);if err!=nil{problem(w,500,"Не удалось удалить событие");return};if result.RowsAffected()==0{problem(w,404,"Событие не найдено");return};if tx.Commit(r.Context())!=nil{problem(w,500,"Не удалось удалить событие");return};w.WriteHeader(http.StatusNoContent)}
func (a *app) reviewFinanceEvent(w http.ResponseWriter,r *http.Request){
	id:=current(r);var in struct{Status string};if !decode(w,r,&in){return};if in.Status!="confirmed"&&in.Status!="rejected"{problem(w,400,"Доступны подтверждение или отклонение");return}
	eventID:=chi.URLParam(r,"id");tx,err:=a.db.Begin(r.Context());if err!=nil{problem(w,500,"Ошибка базы данных");return};defer tx.Rollback(r.Context());var counterpartyID string;err=tx.QueryRow(r.Context(),`SELECT counterparty_id FROM finance_events WHERE id=$1 AND organization_id=$2 AND status='pending' AND deleted_at IS NULL FOR UPDATE`,eventID,id.OrganizationID).Scan(&counterpartyID);if err!=nil{problem(w,404,"Событие не найдено или уже обработано");return}
	if _,err=tx.Exec(r.Context(),`INSERT INTO finance_event_audit(event_id,organization_id,action,snapshot,actor_id) SELECT id,organization_id,'reviewed',to_jsonb(finance_events),$3 FROM finance_events WHERE id=$1 AND organization_id=$2 AND deleted_at IS NULL`,eventID,id.OrganizationID,id.UserID);err!=nil{problem(w,500,"Не удалось записать аудит");return};if _,err=tx.Exec(r.Context(),`UPDATE finance_events SET status=$1,reviewed_by=$2,reviewed_at=now(),updated_at=now() WHERE id=$3`,in.Status,id.UserID,eventID);err!=nil{problem(w,500,"Не удалось обработать событие");return};if err=replaceLedgerEntry(r.Context(),tx,eventID);err!=nil||tx.Commit(r.Context())!=nil{problem(w,500,"Не удалось записать проводку");return};writeJSON(w,200,map[string]string{"status":in.Status})
}

func (a *app) listDeletedFinanceEvents(w http.ResponseWriter,r *http.Request){id:=current(r);rows,err:=a.db.Query(r.Context(),`SELECT id,event_type,amount,project_name,description,event_date,deleted_at FROM finance_events WHERE organization_id=$1 AND deleted_at IS NOT NULL ORDER BY deleted_at DESC LIMIT 500`,id.OrganizationID);if err!=nil{problem(w,500,"Не удалось загрузить удалённые события");return};defer rows.Close();result:=[]map[string]any{};for rows.Next(){var eventID,eventType,projectName,description string;var amount float64;var eventDate time.Time;var deletedAt time.Time;if rows.Scan(&eventID,&eventType,&amount,&projectName,&description,&eventDate,&deletedAt)!=nil{problem(w,500,"Не удалось прочитать удалённое событие");return};result=append(result,map[string]any{"id":eventID,"type":eventType,"amount":amount,"projectName":projectName,"description":description,"eventDate":eventDate.Format("2006-01-02"),"deletedAt":deletedAt})};writeJSON(w,200,result)}
func (a *app) restoreFinanceEvent(w http.ResponseWriter,r *http.Request){id:=current(r);eventID:=chi.URLParam(r,"id");tx,err:=a.db.Begin(r.Context());if err!=nil{problem(w,500,"Ошибка базы данных");return};defer tx.Rollback(r.Context());if _,err=tx.Exec(r.Context(),`INSERT INTO finance_event_audit(event_id,organization_id,action,snapshot,actor_id) SELECT id,organization_id,'restored',to_jsonb(finance_events),$3 FROM finance_events WHERE id=$1 AND organization_id=$2 AND deleted_at IS NOT NULL`,eventID,id.OrganizationID,id.UserID);err!=nil{problem(w,500,"Не удалось записать аудит");return};result,err:=tx.Exec(r.Context(),`UPDATE finance_events SET deleted_at=NULL,deleted_by=NULL,updated_at=now() WHERE id=$1 AND organization_id=$2 AND deleted_at IS NOT NULL`,eventID,id.OrganizationID);if err!=nil{problem(w,500,"Не удалось восстановить событие");return};if result.RowsAffected()==0{problem(w,404,"Удалённое событие не найдено");return};if err=replaceLedgerEntry(r.Context(),tx,eventID);err!=nil||tx.Commit(r.Context())!=nil{problem(w,500,"Не удалось восстановить проводку");return};writeJSON(w,200,map[string]string{"id":eventID})}

func (a *app) authenticate(next http.Handler)http.Handler{return http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){c,err:=r.Cookie(sessionCookie);if err!=nil{problem(w,401,"Требуется вход");return};h:=sha256.Sum256([]byte(c.Value));var id identity;err=a.db.QueryRow(r.Context(),`SELECT u.id,u.email,u.name,o.id,o.name,m.role,COALESCE(m.category,'') FROM sessions s JOIN users u ON u.id=s.user_id JOIN organization_members m ON m.user_id=u.id JOIN organizations o ON o.id=m.organization_id WHERE s.token_hash=$1 AND s.expires_at>now()`,h[:]).Scan(&id.UserID,&id.Email,&id.Name,&id.OrganizationID,&id.OrganizationName,&id.Role,&id.Category);if err!=nil{a.clearCookie(w);problem(w,401,"Сессия истекла");return};next.ServeHTTP(w,r.WithContext(context.WithValue(r.Context(),identityKey,id)))})}
func requireOrganization(next http.Handler)http.Handler{return http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){if current(r).Role!="organization"{problem(w,403,"Недостаточно прав");return};next.ServeHTTP(w,r)})}
func (a *app) newSession(ctx context.Context,w http.ResponseWriter,userID string)error{token:=randomToken();h:=sha256.Sum256([]byte(token));expires:=time.Now().Add(30*24*time.Hour);_,err:=a.db.Exec(ctx,"INSERT INTO sessions(user_id,token_hash,expires_at) VALUES($1,$2,$3)",userID,h[:],expires);if err==nil{http.SetCookie(w,&http.Cookie{Name:sessionCookie,Value:token,Path:"/",HttpOnly:true,Secure:a.secureCookie,SameSite:http.SameSiteLaxMode,Expires:expires,MaxAge:2592000})};return err}
func (a *app) clearCookie(w http.ResponseWriter){http.SetCookie(w,&http.Cookie{Name:sessionCookie,Path:"/",HttpOnly:true,Secure:a.secureCookie,SameSite:http.SameSiteLaxMode,MaxAge:-1})}
func (a *app) loadIdentity(ctx context.Context,userID string,id *identity)error{return a.db.QueryRow(ctx,`SELECT u.id,u.email,u.name,o.id,o.name,m.role,COALESCE(m.category,'') FROM users u JOIN organization_members m ON m.user_id=u.id JOIN organizations o ON o.id=m.organization_id WHERE u.id=$1`,userID).Scan(&id.UserID,&id.Email,&id.Name,&id.OrganizationID,&id.OrganizationName,&id.Role,&id.Category)}
func current(r *http.Request)identity{return r.Context().Value(identityKey).(identity)}
func userResponse(i identity)map[string]string{return map[string]string{"id":i.UserID,"email":i.Email,"name":i.Name,"organizationId":i.OrganizationID,"organizationName":i.OrganizationName,"role":i.Role,"category":i.Category}}
func randomToken()string{b:=make([]byte,32);if _,err:=rand.Read(b);err!=nil{panic(err)};return base64.RawURLEncoding.EncodeToString(b)}
func validCategory(v string)bool{switch v{case "customer","partner","contractor","supplier","employee":return true};return false}
func validFinanceType(v string)bool{switch v{case "receipt","report","transfer","estimate":return true};return false}
func validReceiptDestination(v string)bool{switch v{case "project","agent_fee","company_fund":return true};return false}
func validTransferKind(v string)bool{switch v{case "project_payment","project_accountable","fund_payment","project_to_fund","fund_to_project":return true};return false}
func validDocumentType(v string)bool{switch v{case "acceptance","ks2","balance","expenses","estimate":return true};return false}
func decode(w http.ResponseWriter,r *http.Request,v any)bool{r.Body=http.MaxBytesReader(w,r.Body,1<<20);decoder:=json.NewDecoder(r.Body);decoder.DisallowUnknownFields();if err:=decoder.Decode(v);err!=nil{problem(w,400,"Некорректный запрос");return false};return true}
func writeJSON(w http.ResponseWriter,status int,v any){w.Header().Set("Content-Type","application/json; charset=utf-8");w.WriteHeader(status);_ = json.NewEncoder(w).Encode(v)}
func problem(w http.ResponseWriter,status int,message string){writeJSON(w,status,map[string]string{"error":message})}
func recoverer(next http.Handler)http.Handler{return http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){defer func(){if value:=recover();value!=nil{slog.Error("panic","error",fmt.Sprint(value));problem(w,500,"Внутренняя ошибка")}}();next.ServeHTTP(w,r)})}
func env(key,fallback string)string{if value:=os.Getenv(key);value!=""{return value};return fallback}
func must(err error){if err!=nil{panic(err)}}
