import type { Content, TableCell, TDocumentDefinitions } from 'pdfmake/interfaces'

export type ProjectDocumentType = 'acceptance'|'ks2'|'balance'|'expenses'|'estimate'
export type ProjectDocumentEvent = { id:string;type:'receipt'|'report'|'transfer'|'estimate';amount:number;status:string;projectId:string;projectName:string;description:string;eventDate:string;relatedPartyName:string;expenseCategory?:string;estimatePositions?:string }
export type ProjectDocumentDetails = { fullName:string;inn:string;ogrn:string;registrationAddress:string;actualAddress:string;bankName:string;bankAccount:string;bik:string;correspondentAccount:string }
type Input={type:ProjectDocumentType;project:{name:string;customer:string;address:string};details:ProjectDocumentDetails;contract:{number:string;date:string;customerDetails:string};events:ProjectDocumentEvent[];from:string;to:string}

export function buildProjectDocument(input:Input):TDocumentDefinitions{
 const common={pageSize:'A4' as const,pageMargins:[28,30,28,34] as [number,number,number,number],defaultStyle:{font:'Roboto',fontSize:8},styles:{title:{fontSize:15,bold:true,alignment:'center' as const,margin:[0,4,0,5] as [number,number,number,number]},subtitle:{fontSize:9,alignment:'center' as const,margin:[0,0,0,14] as [number,number,number,number]},section:{fontSize:10,bold:true,margin:[0,14,0,6] as [number,number,number,number]},muted:{fontSize:7,color:'#666'}},footer:(page:number,pages:number)=>({text:`стр. ${page} из ${pages}`,alignment:'center' as const,fontSize:7,color:'#777'})}
 const definitions:Record<ProjectDocumentType,()=>TDocumentDefinitions>={acceptance:()=>({...common,content:acceptance(input)}),ks2:()=>({...common,pageOrientation:'landscape',content:ks2(input)}),balance:()=>({...common,content:balance(input)}),expenses:()=>({...common,content:expenses(input)}),estimate:()=>({...common,content:estimate(input)})}
 return definitions[input.type]()
}

function parties(i:Input):Content{return {table:{widths:[70,'*'],body:[['Исполнитель',`${i.details.fullName}\nИНН ${i.details.inn||'не указан'}, ОГРН ${i.details.ogrn||'не указан'}\n${i.details.registrationAddress||'Адрес не указан'}`],['Заказчик',`${i.project.customer}\n${i.contract.customerDetails||'Реквизиты заказчика не заполнены'}`],['Объект',`${i.project.name}, ${i.project.address}`],['Договор',`№ ${i.contract.number||'б/н'} от ${date(i.contract.date)}`]]},layout:'lightHorizontalLines',margin:[0,8,0,12]}}
function acceptance(i:Input):Content[]{const works=i.events.filter(e=>e.type==='estimate'||e.type==='report');const rows=works.map((e,n)=>[String(n+1),e.description||e.estimatePositions||'Работы по проекту',date(e.eventDate),rub(e.amount)]);return[{text:'АКТ ПРИЁМКИ ВЫПОЛНЕННЫХ РАБОТ',style:'title'},{text:`за период с ${date(i.from)} по ${date(i.to)}`,style:'subtitle'},parties(i),{text:'Исполнитель выполнил, а Заказчик принял следующие работы:',margin:[0,4,0,8]},{table:{headerRows:1,widths:[22,'*',65,75],body:[head(['№','Наименование работ','Дата','Стоимость, руб.']),...empty(rows,4)]},layout:'grid'},{text:`Всего принято работ на сумму: ${rub(sum(works))} руб.`,bold:true,alignment:'right',margin:[0,10,0,0]},{text:'Работы выполнены в полном объёме и в установленный срок. Заказчик претензий к объёму, качеству и срокам выполнения работ не имеет.',margin:[0,16,0,0]},signatures(i)]}
function ks2(i:Input):Content[]{const rows=i.events.filter(e=>e.type==='estimate'||e.type==='report').map((e,n)=>[String(n+1),'',e.description||e.estimatePositions||'Строительно-монтажные работы','', 'шт.','1',rub(e.amount),rub(e.amount)]);return[{columns:[{text:'Унифицированная форма № КС-2',alignment:'right',fontSize:7},{text:'Код',alignment:'right',fontSize:7}],margin:[0,0,0,2]},{columns:[{text:'Утверждена постановлением Госкомстата России от 11.11.1999 № 100',fontSize:7},{table:{widths:[58],body:[['Форма по ОКУД'],['0322005']]},layout:'grid',fontSize:7}],columnGap:10},{text:'АКТ О ПРИЁМКЕ ВЫПОЛНЕННЫХ РАБОТ',style:'title'},{text:`за период с ${date(i.from)} по ${date(i.to)}`,style:'subtitle'},parties(i),{table:{headerRows:2,widths:[20,24,'*',30,34,34,52,60],body:[[cell('Номер'),cell('Номер позиции по смете'),cell('Наименование работ'),cell('Номер единичной расценки'),cell('Ед. изм.'),cell('Количество'),cell('Цена за единицу, руб.'),cell('Стоимость, руб.')],['1','2','3','4','5','6','7','8'],...empty(rows,8)]},layout:'grid',fontSize:6.5},{text:`Итого по акту: ${rub(sum(i.events.filter(e=>e.type==='estimate'||e.type==='report')))} руб.`,bold:true,alignment:'right',margin:[0,8,0,0]},signatures(i)]}
function balance(i:Input):Content[]{let running=0;const rows=i.events.filter(e=>e.type!=='estimate').sort((a,b)=>a.eventDate.localeCompare(b.eventDate)).map((e,n)=>{const incoming=e.type==='receipt';running+=incoming?e.amount:-e.amount;return[String(n+1),date(e.eventDate),title(e),incoming?rub(e.amount):'—',incoming?'—':rub(e.amount),rub(running)]});return[{text:'ДЕТАЛИЗАЦИЯ БАЛАНСА',style:'title'},{text:`Проект «${i.project.name}» · ${date(i.from)}–${date(i.to)}`,style:'subtitle'},parties(i),{table:{headerRows:1,widths:[20,50,'*',62,62,62],body:[head(['№','Дата','Операция','Поступление','Расход','Баланс']),...empty(rows,6)]},layout:'grid'},{text:`Баланс на конец периода: ${rub(running)} руб.`,bold:true,alignment:'right',margin:[0,10,0,0]}]}
function expenses(i:Input):Content[]{const items=i.events.filter(e=>e.type==='report');const rows=items.map((e,n)=>[String(n+1),e.expenseCategory||'Без статьи',e.description||'Расход по проекту',date(e.eventDate),rub(e.amount)]);return[{text:'ВЕДОМОСТЬ РАСХОДОВ ПО СТАТЬЯМ',style:'title'},{text:`Проект «${i.project.name}» · ${date(i.from)}–${date(i.to)}`,style:'subtitle'},parties(i),{table:{headerRows:1,widths:[20,90,'*',58,70],body:[head(['№','Статья','Описание','Дата','Сумма, руб.']),...empty(rows,5)]},layout:'grid'},{text:`Итого расходов: ${rub(sum(items))} руб.`,bold:true,alignment:'right',margin:[0,10,0,0]}]}
function estimate(i:Input):Content[]{const items=i.events.filter(e=>e.type==='estimate');const rows=items.map((e,n)=>[String(n+1),e.estimatePositions||e.description||'Работы и материалы','1',rub(e.amount),rub(e.amount)]);return[{text:'СВОДНЫЙ СМЕТНЫЙ РАСЧЁТ',style:'title'},{text:`Проект «${i.project.name}» · в ценах на ${date(i.to)}`,style:'subtitle'},parties(i),{table:{headerRows:1,widths:[22,'*',55,70,75],body:[head(['№','Наименование работ и затрат','Количество','Цена, руб.','Стоимость, руб.']),...empty(rows,5)]},layout:'grid'},{text:`Итого по смете: ${rub(sum(items))} руб.`,bold:true,alignment:'right',margin:[0,10,0,0]},{text:'Настоящий расчёт является приложением к договору и подлежит согласованию сторонами.',style:'muted',margin:[0,16,0,0]},signatures(i)]}
function signatures(i:Input):Content{return {columns:[{text:`Исполнитель: ${i.details.fullName}\n\n____________ / ____________`},{text:`Заказчик: ${i.project.customer}\n\n____________ / ____________`}],columnGap:35,fontSize:8,margin:[0,34,0,0]}}
function head(values:string[]):TableCell[]{return values.map(text=>({text,bold:true,fillColor:'#ececf2',alignment:'center'}))}
function cell(text:string):TableCell{return{text,bold:true,fillColor:'#ececf2',alignment:'center'}}
function empty(rows:(string|TableCell)[][],columns:number){return rows.length?rows:[[ {text:'Нет подтверждённых данных за выбранный период',colSpan:columns,alignment:'center',color:'#666'},...Array(columns-1).fill('') ]]}
function sum(events:ProjectDocumentEvent[]){return events.reduce((total,event)=>total+event.amount,0)}
function title(e:ProjectDocumentEvent){return e.description||({receipt:'Поступление',report:'Расход',transfer:'Перевод',estimate:'Смета'} as const)[e.type]}
function date(value:string){if(!value)return'не указана';const[y,m,d]=value.split('-');return d&&m&&y?`${d}.${m}.${y}`:value}
function rub(value:number){return new Intl.NumberFormat('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2}).format(value)}
